/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package m.b;

import classe.connexionbd;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import classe.boisson;
import classe.stock;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import static m.b.formmain.*;
import java.sql.ResultSet;


/**
 *
 * @author MHD
 */
public class formstock extends javax.swing.JPanel {

    /**
     * Creates new form formecommande
     */
    public formstock() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        cmbboisson = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        ch24 = new javax.swing.JCheckBox();
        ch12 = new javax.swing.JCheckBox();
        ch6 = new javax.swing.JCheckBox();
        ch1 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablistboisson = new javax.swing.JTable();
        btnactualiser = new javax.swing.JButton();
        btnimprimer = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnnouveau = new javax.swing.JButton();
        btnvalider = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setText("APPROVISONNEMENT");

        jLabel6.setText("Boissons");

        jLabel7.setText("Nombres");

        txtnombre.setEnabled(false);
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });

        cmbboisson.setEnabled(false);
        cmbboisson.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbboissonFocusGained(evt);
            }
        });
        cmbboisson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbboissonActionPerformed(evt);
            }
        });

        jLabel3.setText("Type caisse");

        ch24.setText("24");
        ch24.setEnabled(false);
        ch24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch24ActionPerformed(evt);
            }
        });

        ch12.setText("12");
        ch12.setEnabled(false);
        ch12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch12ActionPerformed(evt);
            }
        });

        ch6.setText("6");
        ch6.setEnabled(false);
        ch6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch6ActionPerformed(evt);
            }
        });

        ch1.setText("1");
        ch1.setEnabled(false);
        ch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnombre)
                            .addComponent(cmbboisson, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ch24, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ch12)
                                .addGap(18, 18, 18)
                                .addComponent(ch6)
                                .addGap(18, 18, 18)
                                .addComponent(ch1)
                                .addGap(0, 55, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbboisson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ch24)
                    .addComponent(ch12)
                    .addComponent(ch6)
                    .addComponent(ch1))
                .addGap(26, 26, 26))
        );

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("                    LISTE BOISSONS EN STOCK");

        tablistboisson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "Boisson", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablistboisson.setEnabled(false);
        jScrollPane1.setViewportView(tablistboisson);

        btnactualiser.setBackground(new java.awt.Color(0, 153, 0));
        btnactualiser.setForeground(new java.awt.Color(255, 255, 255));
        btnactualiser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/actualiser.png"))); // NOI18N
        btnactualiser.setText("Actualiser");
        btnactualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualiserActionPerformed(evt);
            }
        });

        btnimprimer.setBackground(new java.awt.Color(0, 0, 0));
        btnimprimer.setForeground(new java.awt.Color(255, 255, 255));
        btnimprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/print.png"))); // NOI18N
        btnimprimer.setText("Imprimer");
        btnimprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(btnactualiser, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(btnimprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnactualiser)
                    .addComponent(btnimprimer))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        btnnouveau.setBackground(new java.awt.Color(0, 0, 102));
        btnnouveau.setForeground(new java.awt.Color(255, 255, 255));
        btnnouveau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nouveau.png"))); // NOI18N
        btnnouveau.setText("Nouveau");
        btnnouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnouveauActionPerformed(evt);
            }
        });

        btnvalider.setBackground(new java.awt.Color(255, 102, 0));
        btnvalider.setForeground(new java.awt.Color(255, 255, 255));
        btnvalider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/valider.png"))); // NOI18N
        btnvalider.setText("Valider");
        btnvalider.setEnabled(false);
        btnvalider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvaliderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnnouveau, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnvalider, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnouveau)
                    .addComponent(btnvalider))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 51));

        jLabel2.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("    STOCK");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(250, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnactualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualiserActionPerformed
        // TODO add your handling code here:
        try {
        // Récupérer le modèle du tableau
        DefaultTableModel tm = (DefaultTableModel) tablistboisson.getModel();

        // Vider le tableau
        tm.setRowCount(0);

        // Recharger les données depuis la base
        stock.actualiserStock(tm);

        JOptionPane.showMessageDialog(this, "Tableau actualisé avec succès !");
    } catch (Exception e) {
        Logger.getLogger(formstock.class.getName()).log(Level.SEVERE, null, e);
    }

    }//GEN-LAST:event_btnactualiserActionPerformed

    private void btnnouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnouveauActionPerformed
        // TODO add your handling code here:
        cmbboisson.setEnabled(true);
        txtnombre.setEnabled(true);
        ch1.setEnabled(true);
        ch12.setEnabled(true);
        ch6.setEnabled(true);
        ch24.setEnabled(true);
        btnvalider.setEnabled(true);
        btnnouveau.setEnabled(false);
    }//GEN-LAST:event_btnnouveauActionPerformed

    private void btnvaliderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvaliderActionPerformed
        // TODO add your handling code here:  
        txtnombre.setEnabled(false);
        cmbboisson.setEnabled(false);
        btnvalider.setEnabled(false);
        btnnouveau.setEnabled(true);
        ch1.setEnabled(false);
        ch6.setEnabled(false);
        ch12.setEnabled(false);
        ch24.setEnabled(false);
        
    try {
        String boisson = cmbboisson.getSelectedItem().toString();
        int nombres = Integer.parseInt(txtnombre.getText().trim());

        // Vérifier le type de caisse
        int multiplicateur = 1;
        if (ch24.isSelected()) multiplicateur = 24;
        else if (ch12.isSelected()) multiplicateur = 12;
        else if (ch6.isSelected()) multiplicateur = 6;
        else if (ch1.isSelected()) multiplicateur = 1;

        int nombre = nombres * multiplicateur;

        // 👉 Enregistrer dans la base
        stock.validerApprovisionnement(boisson, nombre);

        // 👉 Actualiser le tableau
        DefaultTableModel tm = (DefaultTableModel) tablistboisson.getModel();
        tm.setRowCount(0);
        stock.actualiserStock(tm);

        JOptionPane.showMessageDialog(this, "Approvisionnement validé avec succès !");

        // Réinitialiser les champs
        txtnombre.setText("");
        ch1.setSelected(false);
        ch6.setSelected(false);
        ch12.setSelected(false);
        ch24.setSelected(false);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Veuillez entrer un nombre valide.");
    }   catch (SQLException ex) {
            Logger.getLogger(formstock.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnvaliderActionPerformed

    private void btnimprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimerActionPerformed
        // TODO add your handling code here:                                          
    try {
        // Impression directe du JTable "tabstock" (remplace par le nom exact de ton JTable)
        boolean complete = tablistboisson.print(
            JTable.PrintMode.FIT_WIDTH, 
            new MessageFormat("LISTE DES BOISSONS EN STOCK"), 
            new MessageFormat("Page {0}")
        );

        if (complete) {
            JOptionPane.showMessageDialog(this, "Impression lancée avec succès !");
        } else {
            JOptionPane.showMessageDialog(this, "Impression annulée !");
        }

    } catch (PrinterException pe) {
        JOptionPane.showMessageDialog(this, "Erreur lors de l'impression : " + pe.getMessage());
    }
    }//GEN-LAST:event_btnimprimerActionPerformed

    // IMPRESSION AUTOMATIQUE
//    private void btnimprimerActionPerformed(java.awt.event.ActionEvent evt) {                                            
//    try {
//        // Impression directe du JTable
//        boolean complete = tablistboisson.print(
//            JTable.PrintMode.FIT_WIDTH, 
//            new MessageFormat("LISTE DES BOISSONS DISPONIBLE"), 
//            new MessageFormat("Page {0}")
//        );
//
//        if (complete) {
//            JOptionPane.showMessageDialog(this, "Impression lancée avec succès !");
//        } else {
//            JOptionPane.showMessageDialog(this, "Impression annulée !");
//        }
//
//    } catch (PrinterException pe) {
//        JOptionPane.showMessageDialog(this, "Erreur lors de l'impression : " + pe.getMessage());
//    }
//}
    
    private void cmbboissonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbboissonFocusGained
        // TODO add your handling code here:
                                              
    try {
        Connection c = (Connection) connexionbd.seconnecter();
        Statement st = (Statement) c.createStatement();

        // Vérifie bien que ta colonne dans la table s'appelle "nom"
        ResultSet rs = (ResultSet) st.executeQuery("SELECT nom FROM boisson ORDER BY nom");

        // Vider la liste avant de recharger
        cmbboisson.removeAllItems();

        // Ajouter chaque boisson dans la liste déroulante
        while (rs.next()) {
            cmbboisson.addItem(rs.getString("nom"));
        }

        rs.close();
        st.close();
        c.close();

    } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(formstock.class.getName()).log(Level.SEVERE, null, ex);
    }

    }//GEN-LAST:event_cmbboissonFocusGained

    private void ch24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch24ActionPerformed
        // TODO add your handling code here:
        ch1.setEnabled(false);
        ch6.setEnabled(false);
        ch12.setEnabled(false);
    }//GEN-LAST:event_ch24ActionPerformed

    private void ch12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch12ActionPerformed
        // TODO add your handling code here:
        ch1.setEnabled(false);
        ch6.setEnabled(false);
        ch24.setEnabled(false);
    }//GEN-LAST:event_ch12ActionPerformed

    private void ch6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch6ActionPerformed
        // TODO add your handling code here:
        ch1.setEnabled(false);
        ch12.setEnabled(false);
        ch24.setEnabled(false);
    }//GEN-LAST:event_ch6ActionPerformed

    private void ch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch1ActionPerformed
        // TODO add your handling code here:
         ch6.setEnabled(false);
        ch12.setEnabled(false);
        ch24.setEnabled(false);
    }//GEN-LAST:event_ch1ActionPerformed

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE)){
        getToolkit().beep();
        evt.consume();
    }     
    }//GEN-LAST:event_txtnombreKeyTyped

    private void cmbboissonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbboissonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbboissonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualiser;
    private javax.swing.JButton btnimprimer;
    private javax.swing.JButton btnnouveau;
    private javax.swing.JButton btnvalider;
    private javax.swing.JCheckBox ch1;
    private javax.swing.JCheckBox ch12;
    private javax.swing.JCheckBox ch24;
    private javax.swing.JCheckBox ch6;
    private javax.swing.JComboBox<String> cmbboisson;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablistboisson;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
