/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package m.b;

import classe.caisse;
import classe.statistique;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author MHD
 */
public class formcaisse extends javax.swing.JPanel {
private formstatistiques formstatistiques;



    /**
     * Creates new form formecommande
     */
    public formcaisse() {
        initComponents();
         rafraichirEtatCaisse();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtncaisse = new javax.swing.JTextField();
        txtidcaisse = new javax.swing.JTextField();
        dcreation = new javax.swing.JTextField();
        btnnouveau = new javax.swing.JButton();
        btnvalider = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtmencaisser = new javax.swing.JTextField();
        txtmphysique = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnfermer = new javax.swing.JButton();
        txtecaisse = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel2.setFont(new java.awt.Font("Arial Black", 2, 18)); // NOI18N
        jLabel2.setText("                                           CAISSE");

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setText("        NOUVELLE CAISSE");

        jLabel6.setText("Caisse");

        jLabel7.setText("Id caisse");

        jLabel8.setText("Date creéation");

        txtncaisse.setEnabled(false);
        txtncaisse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtncaisseActionPerformed(evt);
            }
        });

        txtidcaisse.setEnabled(false);

        dcreation.setEnabled(false);

        btnnouveau.setBackground(new java.awt.Color(0, 153, 0));
        btnnouveau.setForeground(new java.awt.Color(255, 255, 255));
        btnnouveau.setText("Nouveau");
        btnnouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnouveauActionPerformed(evt);
            }
        });

        btnvalider.setBackground(new java.awt.Color(153, 153, 0));
        btnvalider.setForeground(new java.awt.Color(255, 255, 255));
        btnvalider.setText("Valider");
        btnvalider.setEnabled(false);
        btnvalider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvaliderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtncaisse)
                            .addComponent(txtidcaisse)
                            .addComponent(dcreation))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnnouveau, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnvalider)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtncaisse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtidcaisse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(dcreation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnouveau)
                    .addComponent(btnvalider))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("                    ETAT CAISSE ");

        jLabel3.setText("Montant encaisser");

        jLabel5.setText("Montant physique");

        txtmencaisser.setEnabled(false);
        txtmencaisser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmencaisserActionPerformed(evt);
            }
        });

        txtmphysique.setEnabled(false);

        jLabel9.setText("Caisse");

        btnfermer.setBackground(new java.awt.Color(0, 0, 0));
        btnfermer.setForeground(new java.awt.Color(255, 255, 255));
        btnfermer.setText("Fermer");
        btnfermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfermerActionPerformed(evt);
            }
        });

        txtecaisse.setEnabled(false);
        txtecaisse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtecaisseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmencaisser)
                            .addComponent(txtmphysique)
                            .addComponent(txtecaisse))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnfermer)
                .addGap(119, 119, 119))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtecaisse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtmencaisser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtmphysique, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnfermer)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnnouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnouveauActionPerformed
        // TODO add your handling code here:

        
    try {
        if (caisse.existeCaisseOuverte()) {
            JOptionPane.showMessageDialog(this,
                "Impossible de créer une nouvelle caisse.\nVeuillez fermer la caisse existante avant d'en ouvrir une autre.",
                "Caisse déjà ouverte",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // Générer automatiquement l’ID et la date
        String newId = new SimpleDateFormat("ddMMyyyyHHmmss").format(new Date());
        txtidcaisse.setText(newId);
        dcreation.setText(new SimpleDateFormat("yyyy-MM-dd").format(new Date()));
        txtncaisse.setText("");
        txtncaisse.setEnabled(true);
        btnvalider.setEnabled(true);
        txtncaisse.requestFocus();

    } catch (Exception e) {
        e.printStackTrace();
    }
        
//                 formstatistiques fs = new formstatistiques();
//        formcaisse fc = new formcaisse(fs);
//
//        fs.setVisible(true);
//        fc.setVisible(true);
//
//        String id = new SimpleDateFormat("ddMMyyyyHHmmss").format(new Date());
//    txtidcaisse.setText(id);
//    dcreation.setText(new SimpleDateFormat("yyyy-MM-dd").format(new Date()));
//    txtncaisse.setText("");
//    txtncaisse.setEnabled(true);
//    btnvalider.setEnabled(true);
//    txtncaisse.requestFocus();
//    try {
//        if (caisse.existeCaisseOuverte()) {
//            JOptionPane.showMessageDialog(this,
//                "Impossible de créer une nouvelle caisse.\nVeuillez fermer la caisse existante avant d'en ouvrir une autre.",
//                "Caisse déjà ouverte",
//                JOptionPane.WARNING_MESSAGE
//            );
//            return;
//        }
//
//        // Générer automatiquement l’ID et la date
//        String newId = new SimpleDateFormat("ddMMyyyyHHmmss").format(new Date());
//        txtidcaisse.setText(newId);
//        dcreation.setText(new SimpleDateFormat("yyyy-MM-dd").format(new Date()));
//        txtncaisse.setText("");
//        txtncaisse.setEnabled(true);
//        btnvalider.setEnabled(true);
//        txtncaisse.requestFocus();
//    } catch (Exception e) {
//        e.printStackTrace();
//    }
//


    }//GEN-LAST:event_btnnouveauActionPerformed

    private void txtmencaisserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmencaisserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmencaisserActionPerformed

    private void txtncaisseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtncaisseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtncaisseActionPerformed

    private void txtecaisseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtecaisseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtecaisseActionPerformed

    private void btnvaliderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvaliderActionPerformed
        // TODO add your handling code here:


         String id = txtidcaisse.getText().trim();
        String nom = txtncaisse.getText().trim();
        String dateCreation = dcreation.getText().trim();

        if (nom.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Veuillez saisir le nom de la caisse.");
            return;
        }

        try {
            caisse.ajouter(id, nom, dateCreation);
            JOptionPane.showMessageDialog(this, "Caisse enregistrée avec succès !");
            txtncaisse.setEnabled(false);
            btnvalider.setEnabled(false);

            // Mettre à jour l'état
            rafraichirEtatCaisse();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erreur lors de l'enregistrement.");
        }

    }//GEN-LAST:event_btnvaliderActionPerformed

    private void btnfermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfermerActionPerformed
     try {
    String id = caisse.getIdCaisseOuverte();
    if (id == null) {
        JOptionPane.showMessageDialog(this, "Aucune caisse ouverte !");
        return;
    }

    String nomCaisse = txtecaisse.getText();
    double montantEncaisse = Double.parseDouble(txtmencaisser.getText());
    double montantPhysique = Double.parseDouble(txtmphysique.getText());

    // 1️⃣ Générer le PDF
    caisse.genererPDF(id, nomCaisse, montantEncaisse, montantPhysique);

    // 2️⃣ Fermer la caisse
    caisse.fermer(id);
    JOptionPane.showMessageDialog(this, "Caisse fermée avec succès. PDF généré automatiquement.");

    rafraichirEtatCaisse();

} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Erreur lors de la fermeture de la caisse.");
}   
//    try {
//        String id = caisse.getIdCaisseOuverte();
//        if (id == null) {
//            JOptionPane.showMessageDialog(this, "Aucune caisse ouverte !");
//            return;
//        }
//
//        String nomCaisse = txtecaisse.getText();
//        double montantEncaisse = Double.parseDouble(txtmencaisser.getText());
//        double montantPhysique = Double.parseDouble(txtmphysique.getText());
//
//        // 1️⃣ Générer le PDF de la caisse (logique existante)
//        caisse.genererPDF(id, nomCaisse, montantEncaisse, montantPhysique);
//
//        // 2️⃣ Imprimer automatiquement les statistiques
//        statistique.imprimerStatistiques(formstatistiques.getTabStatistiques());
//
//        // 3️⃣ Exporter automatiquement les statistiques en CSV
//        statistique.exporterStatistiquesCSV(formstatistiques.getTabStatistiques(), "statistiques_caisse.csv");
//
//        // (optionnel) Exporter aussi en PDF si tu ajoutes une méthode exporterStatistiquesPDF
//        // Statistique.exporterStatistiquesPDF(formStatistique.getTabStatistiques(), "statistiques_caisse.pdf");
//
//        // 4️⃣ Fermer la caisse (logique existante)
//        caisse.fermer(id);
//
//        // 5️⃣ Vider le tableau statistique
//        statistique.viderStatistiques(formstatistiques.getTabStatistiques());
//
//        JOptionPane.showMessageDialog(this, "Caisse fermée avec succès. PDF généré, statistiques imprimées et exportées !");
//        rafraichirEtatCaisse();
//
//    } catch (Exception e) {
//        e.printStackTrace();
//        JOptionPane.showMessageDialog(this, "Erreur lors de la fermeture de la caisse.");
//    }
//        
//      


    }//GEN-LAST:event_btnfermerActionPerformed
private void rafraichirEtatCaisse() {
    try {
        if (caisse.existeCaisseOuverte()) {
            // Une caisse est ouverte → désactiver Nouveau/Valider
            btnnouveau.setEnabled(false);
            btnvalider.setEnabled(false);

            // Récupérer l'ID de la caisse ouverte
            String idCaisse = caisse.getIdCaisseOuverte();
            txtecaisse.setText(idCaisse);
            txtidcaisse.setText(idCaisse); // <-- important pour garder l'ID même après redémarrage

            // Mettre à jour les montants
            double encaisse = caisse.calculerMontantEncaisse();
            double depenses = caisse.calculerDepenses();
            txtmencaisser.setText(String.valueOf(encaisse));
            txtmphysique.setText(String.valueOf(encaisse - depenses));

        } else {
            // Aucune caisse ouverte → activer Nouveau
            btnnouveau.setEnabled(true);
            btnvalider.setEnabled(false);

            // Vider les champs
            txtecaisse.setText("");
            txtidcaisse.setText("");
            txtmencaisser.setText("");
            txtmphysique.setText("");
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this,
            "Erreur lors de la vérification de l'état de la caisse.",
            "Erreur",
            JOptionPane.ERROR_MESSAGE
        );
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnfermer;
    private javax.swing.JButton btnnouveau;
    private javax.swing.JButton btnvalider;
    private javax.swing.JTextField dcreation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtecaisse;
    private javax.swing.JTextField txtidcaisse;
    private javax.swing.JTextField txtmencaisser;
    private javax.swing.JTextField txtmphysique;
    private javax.swing.JTextField txtncaisse;
    // End of variables declaration//GEN-END:variables
}
