/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package m.b;

import classe.boisson;
import static classe.boisson.valider;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MHD
 */
public class formboisson extends javax.swing.JPanel {

    /**
     * Creates new form formboisson
     */
    public formboisson() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnactualiser = new javax.swing.JButton();
        btnimprimer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtboisson = new javax.swing.JTextField();
        btnnouveau = new javax.swing.JButton();
        btnvalider = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablistboisson = new javax.swing.JTable();
        txtpunitaire = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnmofifier = new javax.swing.JButton();
        btnsupprimer = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        btnactualiser.setBackground(new java.awt.Color(204, 204, 0));
        btnactualiser.setForeground(new java.awt.Color(255, 255, 255));
        btnactualiser.setText("Actualiser");
        btnactualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualiserActionPerformed(evt);
            }
        });

        btnimprimer.setBackground(new java.awt.Color(0, 0, 0));
        btnimprimer.setForeground(new java.awt.Color(255, 255, 255));
        btnimprimer.setText("Imprimer");
        btnimprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimerActionPerformed(evt);
            }
        });

        jLabel1.setText("Boisson");

        txtboisson.setEnabled(false);

        btnnouveau.setBackground(new java.awt.Color(0, 0, 102));
        btnnouveau.setForeground(new java.awt.Color(255, 255, 255));
        btnnouveau.setText("Nouveau");
        btnnouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnouveauActionPerformed(evt);
            }
        });

        btnvalider.setBackground(new java.awt.Color(0, 153, 51));
        btnvalider.setForeground(new java.awt.Color(255, 255, 255));
        btnvalider.setText("Valider");
        btnvalider.setEnabled(false);
        btnvalider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvaliderActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setText(" LISTE DES BOISSONS DISPONIBLE");

        tablistboisson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "Boisson", "Prix unitaire"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablistboisson.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablistboissonMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablistboisson);

        txtpunitaire.setEnabled(false);
        txtpunitaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpunitaireActionPerformed(evt);
            }
        });
        txtpunitaire.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpunitaireKeyTyped(evt);
            }
        });

        jLabel3.setText("Prix unitaire");

        btnmofifier.setText("Modifier");
        btnmofifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmofifierActionPerformed(evt);
            }
        });

        btnsupprimer.setText("Supprimer");
        btnsupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsupprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                                .addGap(66, 66, 66)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtpunitaire, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtboisson, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(btnactualiser)
                                    .addGap(28, 28, 28)
                                    .addComponent(btnmofifier)
                                    .addGap(29, 29, 29)
                                    .addComponent(btnsupprimer)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnimprimer))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(btnnouveau)
                        .addGap(98, 98, 98)
                        .addComponent(btnvalider)))
                .addGap(0, 46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnactualiser)
                    .addComponent(btnimprimer)
                    .addComponent(btnmofifier)
                    .addComponent(btnsupprimer))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtboisson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtpunitaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnouveau)
                    .addComponent(btnvalider, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnimprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimerActionPerformed
        // TODO add your handling code here:                                          
    try {
        // Lancer l'impression du tableau
        boolean complete = tablistboisson.print(
            JTable.PrintMode.FIT_WIDTH, 
            new MessageFormat("LISTE DES BOISSONS DISPONIBLE"), 
            new MessageFormat("Page - {0}")
        );

        if (complete) {
            JOptionPane.showMessageDialog(this, "Impression terminée !");
        } else {
            JOptionPane.showMessageDialog(this, "Impression annulée !");
        }

    } catch (PrinterException pe) {
        JOptionPane.showMessageDialog(this, "Erreur lors de l'impression : " + pe.getMessage());
    }

    }//GEN-LAST:event_btnimprimerActionPerformed
// IMPRESSION AUTOMATIQUE
//    private void btnimprimerActionPerformed(java.awt.event.ActionEvent evt) {                                            
//    try {
//        // Impression directe du JTable
//        boolean complete = tablistboisson.print(
//            JTable.PrintMode.FIT_WIDTH, 
//            new MessageFormat("LISTE DES BOISSONS DISPONIBLE"), 
//            new MessageFormat("Page {0}")
//        );
//
//        if (complete) {
//            JOptionPane.showMessageDialog(this, "Impression lancée avec succès !");
//        } else {
//            JOptionPane.showMessageDialog(this, "Impression annulée !");
//        }
//
//    } catch (PrinterException pe) {
//        JOptionPane.showMessageDialog(this, "Erreur lors de l'impression : " + pe.getMessage());
//    }
//}
    private void btnnouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnouveauActionPerformed
        // TODO add your handling code here:
        btnactualiser.setEnabled(true);
        btnvalider.setEnabled(true);
        btnnouveau.setEnabled(false);
        txtboisson.setEnabled(true);
        txtpunitaire.setEnabled(true);
        txtboisson.grabFocus();//AFFECTER LE CURSEUR
    }//GEN-LAST:event_btnnouveauActionPerformed

    private void txtpunitaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpunitaireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpunitaireActionPerformed

    private void btnvaliderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvaliderActionPerformed
        // TODO add your handling code here:
         String nom = txtboisson.getText().trim();
    String pr = txtpunitaire.getText().trim();

    try {
        int prix = Integer.parseInt(pr);
        boisson.valider(nom, prix);

        // 👉 Vider les champs après la validation
        txtboisson.setText("");
        txtpunitaire.setText("");

        // 👉 (optionnel) replacer le curseur dans le premier champ
        txtboisson.requestFocus();

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Veuillez entrer un nombre valide pour le prix.");
    }

    }//GEN-LAST:event_btnvaliderActionPerformed

    private void txtpunitaireKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpunitaireKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE)){
        getToolkit().beep();
        evt.consume();
    }
    }//GEN-LAST:event_txtpunitaireKeyTyped

    private void tablistboissonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablistboissonMouseClicked
        // TODO add your handling code here:
         if(tablistboisson.getRowCount()!=0){
            btnsupprimer.setEnabled(true);
            btnmofifier.setEnabled(true);
            btnvalider.setEnabled(false);
            txtboisson.setEnabled(true);
            txtpunitaire.setEnabled(true);
            txtboisson.setText(tablistboisson.getValueAt(tablistboisson.getSelectedRow(), 1).toString());
            txtpunitaire.setText(tablistboisson.getValueAt(tablistboisson.getSelectedRow(), 1).toString());
        }
    }//GEN-LAST:event_tablistboissonMouseClicked

    private void btnactualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualiserActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tm = (DefaultTableModel) tablistboisson.getModel();
        tm.setRowCount(0);
        boisson.actualiser(tm);
    }//GEN-LAST:event_btnactualiserActionPerformed

    private void btnsupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsupprimerActionPerformed
        // TODO add your handling code here:
         // Vérifier si une ligne est sélectionnée
    int selectedRow = tablistboisson.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Veuillez sélectionner une boisson dans la liste.");
        return;
    }

    // Récupérer le nom de la boisson (colonne 1 = Boisson)
    String nom = tablistboisson.getValueAt(selectedRow, 1).toString();

    // Appeler la méthode supprimer dans ta classe boisson
    boisson.supprimer(nom);

    // Désactiver les boutons après suppression
    btnsupprimer.setEnabled(false);
    btnmofifier.setEnabled(false);

    // Vider les champs du formulaire
    txtboisson.setText("");
    txtpunitaire.setText("");
    txtboisson.requestFocus();

    // Rafraîchir le tableau
    DefaultTableModel tm = (DefaultTableModel) tablistboisson.getModel();
    tm.setRowCount(0); // vider le tableau
    boisson.actualiser(tm); // recharger les données depuis la base

    }//GEN-LAST:event_btnsupprimerActionPerformed

    private void btnmofifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmofifierActionPerformed
        // TODO add your handling code here:
        int selectedRow = tablistboisson.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Veuillez sélectionner une boisson dans la liste.");
        return;
    }

    // Ancien nom (clé primaire) depuis la ligne sélectionnée
    String ancienNom = tablistboisson.getValueAt(selectedRow, 1).toString();

    // Nouvelles valeurs depuis les champs de saisie
    String nouveauNom = txtboisson.getText().trim();
    String nouveauPrixStr = txtpunitaire.getText().trim();

    if (nouveauNom.isEmpty() || nouveauPrixStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs.");
        return;
    }

    try {
        int nouveauPrix = Integer.parseInt(nouveauPrixStr);

        // Appeler la méthode modifier dans ta classe boisson
        boisson.modifier(ancienNom, nouveauNom, nouveauPrix);

        JOptionPane.showMessageDialog(this, "Boisson modifiée avec succès !");
        // Désactiver les boutons après modification
        btnsupprimer.setEnabled(false);
        btnmofifier.setEnabled(false);

        // Vider les champs
        txtboisson.setText("");
        txtpunitaire.setText("");
        txtboisson.requestFocus();

        // Rafraîchir le tableau
        DefaultTableModel tm = (DefaultTableModel) tablistboisson.getModel();
        tm.setRowCount(0);
        boisson.actualiser(tm);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Veuillez entrer un nombre valide pour le prix.");
    }

    }//GEN-LAST:event_btnmofifierActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualiser;
    private javax.swing.JButton btnimprimer;
    private javax.swing.JButton btnmofifier;
    private javax.swing.JButton btnnouveau;
    private javax.swing.JButton btnsupprimer;
    private javax.swing.JButton btnvalider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablistboisson;
    private javax.swing.JTextField txtboisson;
    private javax.swing.JTextField txtpunitaire;
    // End of variables declaration//GEN-END:variables
}
