/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package m.b;

/**
 *
 * @author MHD
 */
public class formparametre extends javax.swing.JPanel {

    /**
     * Creates new form formparametre
     */
    public formparametre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        putilisateur = new javax.swing.JLabel();
        pmotdepasse = new javax.swing.JLabel();
        pprofil = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        pnouveaufrigo = new javax.swing.JLabel();
        dparametre = new javax.swing.JScrollPane();

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        putilisateur.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        putilisateur.setForeground(new java.awt.Color(255, 255, 255));
        putilisateur.setText("Utilsateur");
        putilisateur.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        putilisateur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                putilisateurMouseClicked(evt);
            }
        });

        pmotdepasse.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pmotdepasse.setForeground(new java.awt.Color(255, 255, 255));
        pmotdepasse.setText("Mot de passe");
        pmotdepasse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pmotdepasse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pmotdepasseMouseClicked(evt);
            }
        });

        pprofil.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pprofil.setForeground(new java.awt.Color(255, 255, 255));
        pprofil.setText("Profil");
        pprofil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pprofil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pprofilMouseClicked(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        pnouveaufrigo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pnouveaufrigo.setForeground(new java.awt.Color(255, 255, 255));
        pnouveaufrigo.setText("Nouveau frigo");
        pnouveaufrigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnouveaufrigoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator3)
            .addComponent(jSeparator2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pmotdepasse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(putilisateur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pprofil, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnouveaufrigo, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(putilisateur)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pmotdepasse)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(pprofil)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnouveaufrigo)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        dparametre.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dparametre, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dparametre)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void putilisateurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_putilisateurMouseClicked
        // TODO add your handling code here:
        dparametre.removeAll();// vidé
        dparametre.repaint();//actualisé
        formutilisateur futil = new formutilisateur();
        futil.setSize(dparametre.getWidth(),dparametre.getHeight());
        futil.setVisible(true);
        dparametre.add(futil);
    }//GEN-LAST:event_putilisateurMouseClicked

    private void pmotdepasseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pmotdepasseMouseClicked
        // TODO add your handling code here:
        dparametre.removeAll();// vidé
        dparametre.repaint();//actualisé
        dparametre.revalidate();
        formmotdepasse fmdp = new formmotdepasse();
        fmdp.setSize(dparametre.getWidth(),dparametre.getHeight());
        fmdp.setVisible(true);
        dparametre.add(fmdp);
    }//GEN-LAST:event_pmotdepasseMouseClicked

    private void pprofilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pprofilMouseClicked
        // TODO add your handling code here:
        dparametre.removeAll();// vidé
        dparametre.repaint();//actualisé
        dparametre.revalidate();
        formprofil fprofile = new formprofil();
        fprofile.setSize(dparametre.getWidth(),dparametre.getHeight());
        fprofile.setVisible(true);
        dparametre.add(fprofile);
    }//GEN-LAST:event_pprofilMouseClicked

    private void pnouveaufrigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnouveaufrigoMouseClicked
        // TODO add your handling code here:
         dparametre.removeAll();// vidé
        dparametre.repaint();//actualisé
        dparametre.revalidate();
        formcreefrigo fcree = new formcreefrigo();
        fcree.setSize(dparametre.getWidth(),dparametre.getHeight());
        fcree.setVisible(true);
        dparametre.add(fcree);
    }//GEN-LAST:event_pnouveaufrigoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JScrollPane dparametre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel pmotdepasse;
    private javax.swing.JLabel pnouveaufrigo;
    private javax.swing.JLabel pprofil;
    private javax.swing.JLabel putilisateur;
    // End of variables declaration//GEN-END:variables
}
