/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package m.b;

import classe.commande;
import classe.connexionbd;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;

/**
 *
 * @author MHD
 */
public class formlistcommande extends javax.swing.JFrame {

    /**
     * Creates new form formlistcommande
     */
//    private formlistcommande listForm;
//private formecommande fc;
//
//public formlistcommande(formecommande fc) {
//    initComponents();
//    this.fc = fc; // ✅ on garde la référence
//}
    public formlistcommande() {
//        this.listForm = listForm;
//            this.fc = fc;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablcommande = new javax.swing.JTable();
        btnimprimer = new javax.swing.JButton();
        btnactualiser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        tablcommande.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id commande", "Statut", "Serveur", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablcommande.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablcommandeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablcommande);

        btnimprimer.setBackground(new java.awt.Color(0, 0, 0));
        btnimprimer.setForeground(new java.awt.Color(255, 255, 255));
        btnimprimer.setText("Imprimer");
        btnimprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimerActionPerformed(evt);
            }
        });

        btnactualiser.setBackground(new java.awt.Color(0, 204, 0));
        btnactualiser.setForeground(new java.awt.Color(255, 255, 255));
        btnactualiser.setText("Actualiser");
        btnactualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualiserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(btnactualiser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnimprimer)
                .addGap(141, 141, 141))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnimprimer)
                    .addComponent(btnactualiser))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablcommandeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablcommandeMouseClicked
    formecommande.btnimprimer.setEnabled(true);
    formecommande.chpayer.setEnabled(true);
    formecommande.cmbserveur.setEnabled(true);

    int selectedRow = tablcommande.getSelectedRow();
    if (selectedRow == -1) return;

    String idCommande = tablcommande.getValueAt(selectedRow, 0).toString();

    try {
        Connection c = (Connection) connexionbd.seconnecter();
        PreparedStatement ps = (PreparedStatement) c.prepareStatement(
            "SELECT b.nom, cd.prix, cd.quantite FROM commande_details cd " +
            "JOIN boisson b ON cd.id_boisson = b.id WHERE cd.id_commande = ?"
        );
        ps.setString(1, idCommande);
        ResultSet rs = ps.executeQuery();

        DefaultTableModel model = (DefaultTableModel) formecommande.tabcommande.getModel();
        model.setRowCount(0);

        double total = 0; // ⚡ variable pour calculer le total

        while (rs.next()) {
            double prix = rs.getDouble("prix");
            int quantite = rs.getInt("quantite");
            double sousTotal = prix * quantite;

            model.addRow(new Object[]{
                rs.getString("nom"),
                prix,
                quantite,
                sousTotal
            });

            total += sousTotal; // ⚡ accumuler le total
        }

        // ⚡ Mettre à jour le champ Total dans formecommande
        formecommande.txttotal.setText(total + " FCFA");

        c.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_tablcommandeMouseClicked

    private void btnactualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualiserActionPerformed
        // TODO add your handling code here:
      try {
        Connection c = (Connection) connexionbd.seconnecter();
        Statement st = (Statement) c.createStatement();
        ResultSet rs = st.executeQuery("SELECT id_commande, statut, serveur, date_commande FROM commande");

        DefaultTableModel model = (DefaultTableModel) tablcommande.getModel();
        model.setRowCount(0);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id_commande"),
                rs.getString("statut"),
                rs.getString("serveur"),
                rs.getDate("date_commande")
            });
        }

        c.close();
    } catch (Exception e) {
        e.printStackTrace();
    }


    }//GEN-LAST:event_btnactualiserActionPerformed

    private void btnimprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimerActionPerformed
        // TODO add your handling code here:
         try {
        boolean complete = tablcommande.print();
        if (complete) {
            JOptionPane.showMessageDialog(this, "Impression terminée.");
        } else {
            JOptionPane.showMessageDialog(this, "Impression annulée.");
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erreur lors de l'impression des commandes.");
    }

    }//GEN-LAST:event_btnimprimerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formlistcommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formlistcommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formlistcommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formlistcommande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formlistcommande().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualiser;
    private javax.swing.JButton btnimprimer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tablcommande;
    // End of variables declaration//GEN-END:variables
}
