/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package m.b;

import classe.caisse;
import classe.depense;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.*;

/**
 *
 * @author MHD
 */
public class formdepense extends javax.swing.JPanel {

    /**
     * Creates new form formecommande
     */
    public formdepense() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtmotif = new javax.swing.JTextField();
        txtsomme = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnnouveau = new javax.swing.JButton();
        btnajouter = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabdepense = new javax.swing.JTable();
        btnactualiser = new javax.swing.JButton();
        btnimprimer = new javax.swing.JButton();
        btnreinitialiser = new javax.swing.JButton();
        btnArchives = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setText("NOUVELLE DEPENSE");

        jLabel6.setText("Motif");

        jLabel7.setText("Somme");

        txtmotif.setEnabled(false);
        txtmotif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmotifActionPerformed(evt);
            }
        });

        txtsomme.setEnabled(false);
        txtsomme.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsommeKeyTyped(evt);
            }
        });

        txttotal.setEnabled(false);
        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setText("TOTAL");

        btnnouveau.setBackground(new java.awt.Color(0, 0, 102));
        btnnouveau.setForeground(new java.awt.Color(255, 255, 255));
        btnnouveau.setText("Nouveau");
        btnnouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnouveauActionPerformed(evt);
            }
        });

        btnajouter.setBackground(new java.awt.Color(255, 102, 0));
        btnajouter.setForeground(new java.awt.Color(255, 255, 255));
        btnajouter.setText("Ajouter");
        btnajouter.setEnabled(false);
        btnajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajouterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmotif)
                                    .addComponent(txtsomme)
                                    .addComponent(txttotal)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnnouveau, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addComponent(btnajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtmotif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtsomme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnouveau)
                    .addComponent(btnajouter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33))
        );

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("LISTE DEPENSES RECENTES");

        tabdepense.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Motif", "Somme", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabdepense.setEnabled(false);
        jScrollPane1.setViewportView(tabdepense);

        btnactualiser.setBackground(new java.awt.Color(0, 153, 51));
        btnactualiser.setForeground(new java.awt.Color(255, 255, 255));
        btnactualiser.setText("Actualiser");
        btnactualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualiserActionPerformed(evt);
            }
        });

        btnimprimer.setBackground(new java.awt.Color(0, 0, 0));
        btnimprimer.setForeground(new java.awt.Color(255, 255, 255));
        btnimprimer.setText("Imprimer");
        btnimprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimerActionPerformed(evt);
            }
        });

        btnreinitialiser.setBackground(new java.awt.Color(0, 0, 153));
        btnreinitialiser.setForeground(new java.awt.Color(255, 255, 255));
        btnreinitialiser.setText("Reinitialiser");
        btnreinitialiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreinitialiserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnactualiser)
                .addGap(66, 66, 66)
                .addComponent(btnimprimer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnreinitialiser)
                .addGap(52, 52, 52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnactualiser)
                    .addComponent(btnimprimer)
                    .addComponent(btnreinitialiser))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        btnArchives.setText("Archive");
        btnArchives.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchivesActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 0, 51));

        jLabel2.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("       DEPENSES");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(btnArchives)))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnArchives))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(164, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void btnnouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnouveauActionPerformed
        // TODO add your handling code here:
        txtmotif.setEnabled(true);
        txtsomme.setEnabled(true);
        btnajouter.setEnabled(true);
        btnnouveau.setEnabled(false);
        txtmotif.grabFocus();
    }//GEN-LAST:event_btnnouveauActionPerformed

    private void btnajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajouterActionPerformed

        btnnouveau.setEnabled(true);
        btnajouter.setEnabled(false);
        txtmotif.setEnabled(false);
        txtsomme.setEnabled(false);
        String motif = txtmotif.getText().trim();
    String sommeStr = txtsomme.getText().trim();

    if (motif.isEmpty() || sommeStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs.");
        return;
    }

    try {
        double montant = Double.parseDouble(sommeStr);
        String date = new SimpleDateFormat("yyyy-MM-dd").format(new Date());

        // ✅ Utiliser la nouvelle méthode depense.ajouter qui gère id_caisse
        depense.ajouter(motif, montant, date);

        JOptionPane.showMessageDialog(this, "Dépense ajoutée avec succès !");

        // Mettre à jour le total des dépenses
        double total = depense.calculerTotal();
        txttotal.setText(String.valueOf(total));

        // Rafraîchir la liste des dépenses
        rafraichirListeDepenses();

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Aucune caisse ouverte.");
    }

    }//GEN-LAST:event_btnajouterActionPerformed

    private void txtmotifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmotifActionPerformed
        // TODO add your handling code here:
        txtsomme.grabFocus();
    }//GEN-LAST:event_txtmotifActionPerformed

    private void btnactualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualiserActionPerformed
        // TODO add your handling code here:
         rafraichirListeDepenses(); // méthode déjà définie
    try {
        double total = depense.calculerTotal();
        txttotal.setText(String.valueOf(total));
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erreur lors de l'actualisation.");
    }

    }//GEN-LAST:event_btnactualiserActionPerformed

    private void btnimprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimerActionPerformed
        // TODO add your handling code here:
        try {
        boolean complete = tabdepense.print();
        if (complete) {
            JOptionPane.showMessageDialog(this, "Impression terminée.");
        } else {
            JOptionPane.showMessageDialog(this, "Impression annulée.");
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erreur lors de l'impression.");
    }

    }//GEN-LAST:event_btnimprimerActionPerformed

    private void btnreinitialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreinitialiserActionPerformed
        // TODO add your handling code here:
         txtmotif.setText("");
    txtsomme.setText("");
    txttotal.setText("");

    DefaultTableModel model = (DefaultTableModel) tabdepense.getModel();
    model.setRowCount(0); // vider le tableau

    JOptionPane.showMessageDialog(this, "Formulaire réinitialisé.");

    }//GEN-LAST:event_btnreinitialiserActionPerformed

    private void btnArchivesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivesActionPerformed
        // TODO add your handling code here:
         try {
        ResultSet rs = depense.getDepensesArchive();
        DefaultTableModel model = new DefaultTableModel(new String[]{"Motif", "Montant", "Date Dépense", "Caisse", "Date Archive"}, 0);

        while (rs.next()) {
            Object[] row = {
                rs.getString("motif"),
                rs.getDouble("montant"),
                rs.getDate("date_depense"),
                rs.getString("id_caisse"),
                rs.getTimestamp("date_archive")
            };
            model.addRow(row);
        }

        tabdepense.setModel(model);
        rs.close();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erreur lors du chargement des archives.");
    }

    }//GEN-LAST:event_btnArchivesActionPerformed

    private void txtsommeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsommeKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE)){
        getToolkit().beep();
        evt.consume();
    }     
    }//GEN-LAST:event_txtsommeKeyTyped

private void rafraichirListeDepenses() {
    try {
        // Récupérer l'ID de la caisse ouverte
        String idCaisse = caisse.getIdCaisseOuverte();
        if (idCaisse == null) {
            JOptionPane.showMessageDialog(this, "Aucune caisse ouverte !");
            return;
        }

        // Récupérer uniquement les dépenses de cette caisse
        ResultSet rs = depense.getDepensesRecentes();
        DefaultTableModel model = (DefaultTableModel) tabdepense.getModel();
        model.setRowCount(0); // vider le tableau

        while (rs.next()) {
            Object[] row = {
                rs.getString("motif"),
                rs.getDouble("montant"),
                rs.getDate("date_depense")
            };
            model.addRow(row);
        }
        rs.close();

        // ✅ Mettre à jour le champ TOTAL
        double total = depense.calculerTotal();
        txttotal.setText(String.valueOf(total));

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erreur lors du rafraîchissement de la liste.");
    }
}//private void rafraichirListeDepenses() {
//    try {
//        ResultSet rs = depense.getDepensesRecentes();
//        DefaultTableModel model = (DefaultTableModel) tabdepense.getModel();
//        model.setRowCount(0); // vider le tableau
//
//        while (rs.next()) {
//            Object[] row = {
//                rs.getString("motif"),
//                rs.getDouble("montant"),
//                rs.getDate("date_depense")
//            };
//            model.addRow(row);
//        }
//
//        rs.close();
//    } catch (Exception e) {
//        e.printStackTrace();
//        JOptionPane.showMessageDialog(this, "Erreur lors du rafraîchissement de la liste.");
//    }
//}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArchives;
    private javax.swing.JButton btnactualiser;
    private javax.swing.JButton btnajouter;
    private javax.swing.JButton btnimprimer;
    private javax.swing.JButton btnnouveau;
    private javax.swing.JButton btnreinitialiser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabdepense;
    private javax.swing.JTextField txtmotif;
    private javax.swing.JTextField txtsomme;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
