/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package m.b;

import classe.connexionbd;
import classe.profil;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import static m.b.formparametre.dparametre;
import java.sql.ResultSet;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author MHD
 */
public class formprofil extends javax.swing.JPanel {

    /**
     * Creates new form formutilisateur
     */
    public formprofil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtprofil = new javax.swing.JTextField();
        btnnouveau = new javax.swing.JButton();
        btnvalider = new javax.swing.JButton();
        chcommande = new javax.swing.JCheckBox();
        chdepense = new javax.swing.JCheckBox();
        chfrigo = new javax.swing.JCheckBox();
        chcaisse = new javax.swing.JCheckBox();
        chstock = new javax.swing.JCheckBox();
        chagent = new javax.swing.JCheckBox();
        chstatistique = new javax.swing.JCheckBox();
        chparametre = new javax.swing.JCheckBox();
        chboisson = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        chcommande_liste = new javax.swing.JCheckBox();
        chdepense_liste = new javax.swing.JCheckBox();
        chfrigo_liste = new javax.swing.JCheckBox();
        chcaisse_liste = new javax.swing.JCheckBox();
        chstock_liste = new javax.swing.JCheckBox();
        chagent_liste = new javax.swing.JCheckBox();
        chstatistique_liste = new javax.swing.JCheckBox();
        chparametre_liste = new javax.swing.JCheckBox();
        chboisson_liste = new javax.swing.JCheckBox();
        cmbprofil = new javax.swing.JComboBox<>();
        btnmodifier = new javax.swing.JButton();
        btnsupprimer = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setEnabled(false);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("Profil");

        txtprofil.setEnabled(false);

        btnnouveau.setBackground(new java.awt.Color(153, 0, 0));
        btnnouveau.setForeground(new java.awt.Color(255, 255, 255));
        btnnouveau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nouveau.png"))); // NOI18N
        btnnouveau.setText("Nouveau");
        btnnouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnouveauActionPerformed(evt);
            }
        });

        btnvalider.setBackground(new java.awt.Color(0, 153, 51));
        btnvalider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/valider.png"))); // NOI18N
        btnvalider.setText("Valider");
        btnvalider.setEnabled(false);
        btnvalider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvaliderActionPerformed(evt);
            }
        });

        chcommande.setText("commande");
        chcommande.setEnabled(false);

        chdepense.setText("depense");
        chdepense.setEnabled(false);

        chfrigo.setText("frigo");
        chfrigo.setEnabled(false);

        chcaisse.setText("caisse");
        chcaisse.setEnabled(false);

        chstock.setText("stock");
        chstock.setEnabled(false);

        chagent.setText("agent");
        chagent.setEnabled(false);

        chstatistique.setText("statistique");
        chstatistique.setEnabled(false);

        chparametre.setText("parametre");
        chparametre.setEnabled(false);

        chboisson.setText("boisson");
        chboisson.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chcommande)
                            .addComponent(chcaisse)
                            .addComponent(chboisson))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chdepense)
                            .addComponent(chstock))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(chagent)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chparametre))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(chfrigo)
                                .addGap(18, 18, 18)
                                .addComponent(chstatistique))))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(btnnouveau)
                            .addGap(120, 120, 120)
                            .addComponent(btnvalider))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtprofil, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtprofil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chcommande)
                    .addComponent(chdepense)
                    .addComponent(chfrigo)
                    .addComponent(chstatistique))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chstock)
                    .addComponent(chcaisse)
                    .addComponent(chagent)
                    .addComponent(chparametre))
                .addGap(9, 9, 9)
                .addComponent(chboisson)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnouveau)
                    .addComponent(btnvalider))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Arial Black", 2, 18)); // NOI18N
        jLabel5.setText("        CREER PROFIL UTILISATEUR");

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("Profil");

        chcommande_liste.setText("commande");
        chcommande_liste.setEnabled(false);

        chdepense_liste.setText("depense");
        chdepense_liste.setEnabled(false);
        chdepense_liste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chdepense_listeActionPerformed(evt);
            }
        });

        chfrigo_liste.setText("frigo");
        chfrigo_liste.setEnabled(false);

        chcaisse_liste.setText("caisse");
        chcaisse_liste.setEnabled(false);

        chstock_liste.setText("stock");
        chstock_liste.setEnabled(false);

        chagent_liste.setText("agent");
        chagent_liste.setEnabled(false);

        chstatistique_liste.setText("statistique");
        chstatistique_liste.setEnabled(false);

        chparametre_liste.setText("parametre");
        chparametre_liste.setEnabled(false);

        chboisson_liste.setText("boisson");
        chboisson_liste.setEnabled(false);
        chboisson_liste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chboisson_listeActionPerformed(evt);
            }
        });

        cmbprofil.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbprofilFocusGained(evt);
            }
        });
        cmbprofil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbprofilActionPerformed(evt);
            }
        });

        btnmodifier.setBackground(new java.awt.Color(153, 153, 0));
        btnmodifier.setForeground(new java.awt.Color(255, 255, 255));
        btnmodifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/modi.png"))); // NOI18N
        btnmodifier.setText("Modifier");
        btnmodifier.setEnabled(false);
        btnmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifierActionPerformed(evt);
            }
        });

        btnsupprimer.setBackground(new java.awt.Color(153, 0, 0));
        btnsupprimer.setForeground(new java.awt.Color(255, 255, 255));
        btnsupprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/supprimer_24.png"))); // NOI18N
        btnsupprimer.setText("Supprimer");
        btnsupprimer.setEnabled(false);
        btnsupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsupprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chcommande_liste)
                            .addComponent(chcaisse_liste)
                            .addComponent(chboisson_liste))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chdepense_liste)
                                    .addComponent(chstock_liste))
                                .addGap(18, 18, 18)
                                .addComponent(chfrigo_liste)
                                .addGap(18, 18, 18)
                                .addComponent(chstatistique_liste))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(chagent_liste)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chparametre_liste))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(cmbprofil, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(btnmodifier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnsupprimer)
                .addGap(55, 55, 55))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbprofil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chcommande_liste)
                    .addComponent(chdepense_liste)
                    .addComponent(chfrigo_liste)
                    .addComponent(chstatistique_liste))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chstock_liste)
                    .addComponent(chcaisse_liste)
                    .addComponent(chagent_liste)
                    .addComponent(chparametre_liste))
                .addGap(9, 9, 9)
                .addComponent(chboisson_liste)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnsupprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnmodifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Arial Black", 2, 18)); // NOI18N
        jLabel6.setText("         LISTE PROFIL UTILISATEUR");

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NOUVEAU PROFIL");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(158, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnvaliderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvaliderActionPerformed
        // TODO add your handling code here:
        
         chcommande_liste.setEnabled(true);
    chdepense_liste.setEnabled(true);
    chfrigo_liste.setEnabled(true);
    chboisson_liste.setEnabled(true);
    chcaisse_liste.setEnabled(true);
    chstock_liste.setEnabled(true);
    chagent_liste.setEnabled(true);
    chstatistique_liste.setEnabled(true);
    chparametre_liste.setEnabled(true);
    btnsupprimer.setEnabled(true);
    btnmodifier.setEnabled(true);
    
         String droit = txtprofil.getText().trim();
    int v1 = chcommande.isSelected() ? 1 : 0;
    int v2 = chdepense.isSelected() ? 1 : 0;
    int v3 = chfrigo.isSelected() ? 1 : 0;
    int v4 = chboisson.isSelected() ? 1 : 0;
    int v5 = chcaisse.isSelected() ? 1 : 0;
    int v6 = chstock.isSelected() ? 1 : 0;
    int v7 = chagent.isSelected() ? 1 : 0;
    int v8 = chstatistique.isSelected() ? 1 : 0;
    int v9 = chparametre.isSelected() ? 1 : 0;

        try {
            profil.valider(droit, v1, v2, v3, v4, v5, v6, v7, v8, v9);
        } catch (SQLException ex) {
            Logger.getLogger(formprofil.class.getName()).log(Level.SEVERE, null, ex);
        }

    // Recharger l’interface
    dparametre.removeAll();
    dparametre.repaint();
    dparametre.revalidate();
    formprofil fpro = new formprofil();
    fpro.setSize(dparametre.getWidth(),dparametre.getHeight());
    fpro.setVisible(true);
    dparametre.add(fpro);

    }//GEN-LAST:event_btnvaliderActionPerformed

    private void btnnouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnouveauActionPerformed
        // TODO add your handling code here:
    txtprofil.setEnabled(true);
    chcommande.setEnabled(true);
    chdepense.setEnabled(true);
    chfrigo.setEnabled(true);
    chboisson.setEnabled(true);
    chcaisse.setEnabled(true);
    chstock.setEnabled(true);
    chagent.setEnabled(true);
    chstatistique.setEnabled(true);
    chparametre.setEnabled(true);
    btnvalider.setEnabled(true);
    btnnouveau.setEnabled(false);

    chcommande_liste.setEnabled(false);
    chdepense_liste.setEnabled(false);
    chfrigo_liste.setEnabled(false);
    chboisson_liste.setEnabled(false);
    chcaisse_liste.setEnabled(false);
    chstock_liste.setEnabled(false);
    chagent_liste.setEnabled(false);
    chstatistique_liste.setEnabled(false);
    chparametre_liste.setEnabled(false);
    btnsupprimer.setEnabled(false);
    btnmodifier.setEnabled(false);
    cmbprofil.setEnabled(false);
    }//GEN-LAST:event_btnnouveauActionPerformed

    private void cmbprofilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbprofilActionPerformed
        // TODO add your handling code here:
    // Désactiver ou activer les composants selon ton besoin
    txtprofil.setEnabled(false);
    chcommande.setEnabled(false);
    chdepense.setEnabled(false);
    chfrigo.setEnabled(false);
    chboisson.setEnabled(false);
    chcaisse.setEnabled(false);
    chstock.setEnabled(false);
    chagent.setEnabled(false);
    chstatistique.setEnabled(false);
    chparametre.setEnabled(false);
    btnvalider.setEnabled(false);
    btnnouveau.setEnabled(true);
    
    chcommande_liste.setEnabled(true);
    chdepense_liste.setEnabled(true);
    chfrigo_liste.setEnabled(true);
    chboisson_liste.setEnabled(true);
    chcaisse_liste.setEnabled(true);
    chstock_liste.setEnabled(true);
    chagent_liste.setEnabled(true);
    chstatistique_liste.setEnabled(true);
    chparametre_liste.setEnabled(true);
    btnsupprimer.setEnabled(true);
    btnmodifier.setEnabled(true);
 String droit = cmbprofil.getSelectedItem() != null ? cmbprofil.getSelectedItem().toString() : null;
    if (droit == null || droit.isEmpty()) return;

    try {
        Connection c = (Connection) connexionbd.seconnecter();
        PreparedStatement ps = (PreparedStatement) c.prepareStatement("SELECT * FROM profil WHERE droit = ?");
        ps.setString(1, droit);
        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            chcommande_liste.setSelected(rs.getInt("commande") == 1);
            chdepense_liste.setSelected(rs.getInt("depense") == 1);
            chfrigo_liste.setSelected(rs.getInt("frigo") == 1);
            chboisson_liste.setSelected(rs.getInt("boisson") == 1);
            chcaisse_liste.setSelected(rs.getInt("caisse") == 1);
            chstock_liste.setSelected(rs.getInt("stock") == 1);
            chagent_liste.setSelected(rs.getInt("agent") == 1);
            chstatistique_liste.setSelected(rs.getInt("statistique") == 1);
            chparametre_liste.setSelected(rs.getInt("parametre") == 1);
        }

        rs.close();
        ps.close();
        c.close();
    } catch (Exception e) {
        Logger.getLogger(formprofil.class.getName()).log(Level.SEVERE, null, e);
        JOptionPane.showMessageDialog(this, "Erreur lors de la lecture du profil.");
    }


    }//GEN-LAST:event_cmbprofilActionPerformed

    private void btnsupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsupprimerActionPerformed
        // TODO add your handling code here:
        btnnouveau.setEnabled(true);
       String droit = cmbprofil.getSelectedItem() != null ? cmbprofil.getSelectedItem().toString() : null;
    if (droit == null || droit.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Veuillez sélectionner un profil à supprimer.");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this, "Supprimer le profil \"" + droit + "\" ?", "Confirmation", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        profil.supprimer(droit);
        cmbprofil.removeItem(droit); // Retirer du ComboBox
        chargerComboProfil(); // Mettre à jour le tableau
        reinitialiserCasesListeProfil();
        JOptionPane.showMessageDialog(this, "Profil supprimé.");
    }

    }//GEN-LAST:event_btnsupprimerActionPerformed

    private void btnmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifierActionPerformed
        // TODO add your handling code here:
         btnnouveau.setEnabled(true);
    String droit = cmbprofil.getSelectedItem() != null ? cmbprofil.getSelectedItem().toString() : null;
    if (droit == null || droit.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Aucun profil sélectionné.");
        return;
    }

    int v1 = chcommande_liste.isSelected() ? 1 : 0;
    int v2 = chdepense_liste.isSelected() ? 1 : 0;
    int v3 = chfrigo_liste.isSelected() ? 1 : 0;
    int v4 = chboisson_liste.isSelected() ? 1 : 0;
    int v5 = chcaisse_liste.isSelected() ? 1 : 0;
    int v6 = chstock_liste.isSelected() ? 1 : 0;
    int v7 = chagent_liste.isSelected() ? 1 : 0;
    int v8 = chstatistique_liste.isSelected() ? 1 : 0;
    int v9 = chparametre_liste.isSelected() ? 1 : 0;

    profil.mettreAJour(droit, v1, v2, v3, v4, v5, v6, v7, v8, v9);
    chargerComboProfil(); // recharge le tableau
    reinitialiserCasesListeProfil();
    JOptionPane.showMessageDialog(this, "Profil mis à jour !");

    }//GEN-LAST:event_btnmodifierActionPerformed

    private void cmbprofilFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbprofilFocusGained
        // TODO add your handling code here:
   try {
        Connection c = (Connection) connexionbd.seconnecter();
        Statement st = c.createStatement();
        ResultSet rs = st.executeQuery("SELECT droit FROM profil ORDER BY droit");

        cmbprofil.removeAllItems(); // Vider la liste déroulante

        while (rs.next()) {
            cmbprofil.addItem(rs.getString("droit")); // Ajouter chaque profil
        }

        rs.close();
        st.close();
        c.close();
    } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(formprofil.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Erreur lors du chargement des profils.");
    }

    }//GEN-LAST:event_cmbprofilFocusGained

    private void chdepense_listeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chdepense_listeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chdepense_listeActionPerformed

    private void chboisson_listeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chboisson_listeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chboisson_listeActionPerformed

private void chargerComboProfil() {
    cmbprofil.removeAllItems(); // Vide le ComboBox

    Vector<String> profils = profil.getListeProfils(); // Appel à la méthode métier
    if (profils != null && !profils.isEmpty()) {
        for (String p : profils) {
            cmbprofil.addItem(p); // Ajoute chaque profil au ComboBox
        }
    } else {
        JOptionPane.showMessageDialog(this, "Aucun profil trouvé dans la base de données.");
    }
}

private void reinitialiserCasesListeProfil() {
    chcommande_liste.setSelected(false);
    chdepense_liste.setSelected(false);
    chfrigo_liste.setSelected(false);
    chboisson_liste.setSelected(false);
    chcaisse_liste.setSelected(false);
    chstock_liste.setSelected(false);
    chagent_liste.setSelected(false);
    chstatistique_liste.setSelected(false);
    chparametre_liste.setSelected(false);
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnmodifier;
    private javax.swing.JButton btnnouveau;
    private javax.swing.JButton btnsupprimer;
    private javax.swing.JButton btnvalider;
    private javax.swing.JCheckBox chagent;
    private javax.swing.JCheckBox chagent_liste;
    private javax.swing.JCheckBox chboisson;
    private javax.swing.JCheckBox chboisson_liste;
    private javax.swing.JCheckBox chcaisse;
    private javax.swing.JCheckBox chcaisse_liste;
    private javax.swing.JCheckBox chcommande;
    private javax.swing.JCheckBox chcommande_liste;
    private javax.swing.JCheckBox chdepense;
    private javax.swing.JCheckBox chdepense_liste;
    private javax.swing.JCheckBox chfrigo;
    private javax.swing.JCheckBox chfrigo_liste;
    private javax.swing.JCheckBox chparametre;
    private javax.swing.JCheckBox chparametre_liste;
    private javax.swing.JCheckBox chstatistique;
    private javax.swing.JCheckBox chstatistique_liste;
    private javax.swing.JCheckBox chstock;
    private javax.swing.JCheckBox chstock_liste;
    private javax.swing.JComboBox<String> cmbprofil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtprofil;
    // End of variables declaration//GEN-END:variables
}
