/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package m.b;

import classe.connexionbd;
import classe.creefrigo;
import classe.frigo;
import static classe.frigo.chargerFrigosDansCombo;
import static classe.frigo.getIdBoissonParNom;
import classe.listefrigo;
import classe.stock;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import javax.swing.JTable;



/**
 *
 * @author MHD
 */
public class formfrigo extends javax.swing.JPanel {

    /**
     * Creates new form formecommande
     */
    public formfrigo() {
        initComponents();
//        btnnouveau.setEnabled(false); // désactivé au démarrage
        chargerFrigosDansCombo(cbofrigo);
    }
private void formWindowOpened(java.awt.event.WindowEvent evt) {
    frigo.chargerFrigosDansCombo(cbofrigo);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        cmbboisson = new javax.swing.JComboBox<>();
        btnravitailler = new javax.swing.JButton();
        btnnouveau = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ch24 = new javax.swing.JCheckBox();
        ch12 = new javax.swing.JCheckBox();
        ch6 = new javax.swing.JCheckBox();
        ch1 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablistboisson = new javax.swing.JTable();
        btnactualiser = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnimprimer = new javax.swing.JButton();
        cbofrigo = new javax.swing.JComboBox<>();
        btnreinitialiser = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel2.setFont(new java.awt.Font("Arial Black", 2, 18)); // NOI18N
        jLabel2.setText("                                                    FRIGO");

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setText("                   RAVITAILLEMENT");

        jLabel6.setText("Boissons");

        jLabel7.setText("Nombres");

        txtnombre.setEnabled(false);

        cmbboisson.setEnabled(false);
        cmbboisson.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbboissonFocusGained(evt);
            }
        });
        cmbboisson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbboissonActionPerformed(evt);
            }
        });

        btnravitailler.setBackground(new java.awt.Color(255, 102, 0));
        btnravitailler.setForeground(new java.awt.Color(255, 255, 255));
        btnravitailler.setText("Ravitailler");
        btnravitailler.setEnabled(false);
        btnravitailler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnravitaillerActionPerformed(evt);
            }
        });

        btnnouveau.setBackground(new java.awt.Color(0, 0, 102));
        btnnouveau.setForeground(new java.awt.Color(255, 255, 255));
        btnnouveau.setText("Nouveau");
        btnnouveau.setEnabled(false);
        btnnouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnouveauActionPerformed(evt);
            }
        });

        jLabel3.setText("Type caisse");

        ch24.setText("24");
        ch24.setEnabled(false);
        ch24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch24ActionPerformed(evt);
            }
        });

        ch12.setText("12");
        ch12.setEnabled(false);
        ch12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch12ActionPerformed(evt);
            }
        });

        ch6.setText("6");
        ch6.setEnabled(false);
        ch6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch6ActionPerformed(evt);
            }
        });

        ch1.setText("1");
        ch1.setEnabled(false);
        ch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ch1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnombre)
                            .addComponent(cmbboisson, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnnouveau)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnravitailler, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(ch24, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ch12)
                                .addGap(18, 18, 18)
                                .addComponent(ch6)
                                .addGap(18, 18, 18)
                                .addComponent(ch1)))
                        .addGap(25, 25, 25)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbboisson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ch24)
                    .addComponent(ch12)
                    .addComponent(ch6)
                    .addComponent(ch1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnouveau)
                    .addComponent(btnravitailler))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("            LISTE BOISSONS DU FRIGO");

        tablistboisson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "Boisson", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablistboisson.setEnabled(false);
        tablistboisson.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablistboissonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablistboisson);

        btnactualiser.setBackground(new java.awt.Color(204, 153, 0));
        btnactualiser.setForeground(new java.awt.Color(255, 255, 255));
        btnactualiser.setText("Actualiser");
        btnactualiser.setEnabled(false);
        btnactualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualiserActionPerformed(evt);
            }
        });

        jLabel5.setText("Frigo");

        btnimprimer.setBackground(new java.awt.Color(0, 0, 0));
        btnimprimer.setForeground(new java.awt.Color(255, 255, 255));
        btnimprimer.setText("Imprimer");
        btnimprimer.setEnabled(false);
        btnimprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimerActionPerformed(evt);
            }
        });

        cbofrigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbofrigoFocusGained(evt);
            }
        });
        cbofrigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbofrigoActionPerformed(evt);
            }
        });

        btnreinitialiser.setBackground(new java.awt.Color(153, 0, 0));
        btnreinitialiser.setForeground(new java.awt.Color(255, 255, 255));
        btnreinitialiser.setText("Reinitialiser");
        btnreinitialiser.setEnabled(false);
        btnreinitialiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreinitialiserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnactualiser)
                        .addGap(54, 54, 54)
                        .addComponent(btnimprimer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnreinitialiser)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbofrigo, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbofrigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnactualiser)
                    .addComponent(btnimprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnreinitialiser))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnactualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualiserActionPerformed
        // TODO add your handling code here: 
        String nomFrigo = cbofrigo.getSelectedItem() != null ? cbofrigo.getSelectedItem().toString() : null;
if (nomFrigo != null) {
    String identifiant = creefrigo.getIdentifiantParNom(nomFrigo);
    if (identifiant != null) {
        DefaultTableModel tm = (DefaultTableModel) tablistboisson.getModel();
        frigo.actualiserBoissonsDuFrigo(identifiant, tm);
    }
}
    }//GEN-LAST:event_btnactualiserActionPerformed

    private void btnnouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnouveauActionPerformed
        // TODO add your handling code here:
        btnravitailler.setEnabled(true);
        btnreinitialiser.setEnabled(false);
        txtnombre.setEnabled(true);
        ch1.setEnabled(true);
        ch12.setEnabled(true);
        ch24.setEnabled(true);
        ch6.setEnabled(true);
        btnactualiser.setEnabled(false);
        btnimprimer.setEnabled(false);
        btnnouveau.setEnabled(false);
        cmbboisson.setEnabled(true);
        
    }//GEN-LAST:event_btnnouveauActionPerformed

    private void btnravitaillerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnravitaillerActionPerformed
    try {
        String boisson = cmbboisson.getSelectedItem().toString();
        int nombres = Integer.parseInt(txtnombre.getText().trim());

        int multiplicateur = ch24.isSelected() ? 24 :
                             ch12.isSelected() ? 12 :
                             ch6.isSelected() ? 6 : 1;

        int nombre = nombres * multiplicateur;

        // ✅ Extraire l’ID du frigo avant le tiret
        String frigoSelectionne = cbofrigo.getSelectedItem().toString();
        String idFrigo = frigoSelectionne.split(" - ")[0];

        // ✅ Récupérer l’ID de la boisson par son nom
        int idBoisson = getIdBoissonParNom(boisson);

        // ✅ Appeler la méthode corrigée
        frigo.ravitaillerDepuisStock(idFrigo, idBoisson, nombre);

        // ✅ Recharger les boissons du frigo
        chargerBoissonsDuFrigo(idFrigo);

        JOptionPane.showMessageDialog(this, "Ravitaillement effectué !");
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erreur lors du ravitaillement.");
    }
    }//GEN-LAST:event_btnravitaillerActionPerformed

    private void ch24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch24ActionPerformed
        // TODO add your handling code here:
        ch1.setEnabled(false);
        ch6.setEnabled(false);
        ch12.setEnabled(false);
    }//GEN-LAST:event_ch24ActionPerformed

    private void ch12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch12ActionPerformed
        // TODO add your handling code here:
        ch1.setEnabled(false);
        ch6.setEnabled(false);
        ch24.setEnabled(false);
    }//GEN-LAST:event_ch12ActionPerformed

    private void ch6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch6ActionPerformed
        // TODO add your handling code here:
        ch1.setEnabled(false);
        ch12.setEnabled(false);
        ch24.setEnabled(false);
    }//GEN-LAST:event_ch6ActionPerformed

    private void ch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ch1ActionPerformed
        // TODO add your handling code here:
        ch6.setEnabled(false);
        ch12.setEnabled(false);
        ch24.setEnabled(false);
    }//GEN-LAST:event_ch1ActionPerformed

    private void cmbboissonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbboissonFocusGained
        // TODO add your handling code here:
            // TODO add your handling code here:
                                              
    try {
        Connection c = (Connection) connexionbd.seconnecter();
        Statement st = (Statement) c.createStatement();

        // Vérifie bien que ta colonne dans la table s'appelle "nom"
        ResultSet rs = (ResultSet) st.executeQuery("SELECT nom FROM boisson ORDER BY nom");

        // Vider la liste avant de recharger
        cmbboisson.removeAllItems();

        // Ajouter chaque boisson dans la liste déroulante
        while (rs.next()) {
            cmbboisson.addItem(rs.getString("nom"));
        }

        rs.close();
        st.close();
        c.close();

    } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(formstock.class.getName()).log(Level.SEVERE, null, ex);
    }

    }//GEN-LAST:event_cmbboissonFocusGained
        
    private formlistefrigo panelListe;
   public formfrigo(formlistefrigo panelListe) {
    initComponents();
    this.panelListe = panelListe;

    // Charger les frigos dans la liste déroulante
    creefrigo.chargerFrigosDansCombo(cbofrigo);

    // Vider le tableau des boissons
    DefaultTableModel model = (DefaultTableModel) tablistboisson.getModel();
    model.setRowCount(0);
}

 private void imprimerTableauBoissons() {
    try {
        // Récupérer le nom du frigo sélectionné
        String nomFrigo = cbofrigo.getSelectedItem() != null ? cbofrigo.getSelectedItem().toString() : "Inconnu";

        // Titre avec le nom du frigo
        String titre = "LISTE DES BOISSONS DU FRIGO \"" + nomFrigo + "\"";

        // Pied de page avec la date actuelle
        String date = java.time.LocalDate.now().toString(); // Format: YYYY-MM-DD
        String piedDePage = "Imprimé le " + date + " - Page {0}";

        boolean complete = tablistboisson.print(
            JTable.PrintMode.FIT_WIDTH,
            new java.text.MessageFormat(titre),
            new java.text.MessageFormat(piedDePage)
        );

        if (complete) {
            JOptionPane.showMessageDialog(this, "Impression lancée avec succès !");
        } else {
            JOptionPane.showMessageDialog(this, "Impression annulée !");
        }

    } catch (java.awt.print.PrinterException pe) {
        JOptionPane.showMessageDialog(this, "Erreur lors de l'impression : " + pe.getMessage());
    }
}


    private void btnimprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimerActionPerformed
//        // TODO add your handling code here: 
imprimerTableauBoissons();

    }//GEN-LAST:event_btnimprimerActionPerformed

    private void tablistboissonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablistboissonMouseClicked
        // TODO add your handling code here:                                     
    }//GEN-LAST:event_tablistboissonMouseClicked

public void chargerBoissonsDuFrigo(String idFrigo) {
    try {
        java.sql.Connection c = connexionbd.seconnecter();

        String sql = "SELECT b.nom, bf.stock " +
                     "FROM boisson_frigo bf " +
                     "JOIN boisson b ON bf.id_boisson = b.id " +
                     "WHERE bf.id_frigo = ?";

        PreparedStatement ps = (PreparedStatement) c.prepareStatement(sql);
        ps.setString(1, idFrigo);

        ResultSet rs = ps.executeQuery();

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Boisson");
        model.addColumn("Stock");

        while (rs.next()) {

            String nomBoisson = rs.getString("nom");
            int stock = rs.getInt("stock");

            model.addRow(new Object[]{nomBoisson, stock});
        }

        tablistboisson.setModel(model);

        rs.close();
        ps.close();
        c.close();

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Erreur lors du chargement des boissons du frigo !");
    }
}
    private void cbofrigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbofrigoFocusGained
         // Désactiver certains boutons/champs
    btnravitailler.setEnabled(false);
    btnreinitialiser.setEnabled(true);
    txtnombre.setEnabled(false);
    ch1.setEnabled(false);
    ch12.setEnabled(false);
    ch24.setEnabled(false);
    ch6.setEnabled(false);
    btnactualiser.setEnabled(true);
    btnimprimer.setEnabled(true);
    btnnouveau.setEnabled(true);
    cmbboisson.setEnabled(false);

    try {
        Connection c = (Connection) connexionbd.seconnecter();
        Statement st = (Statement) c.createStatement();

        // ✅ Charger depuis la vraie table frigo
        ResultSet rs = (ResultSet) st.executeQuery("SELECT idFrigo, nom_frigo FROM frigo ORDER BY idFrigo");

        // Vider la liste avant de recharger
        cbofrigo.removeAllItems();
        // Ajouter chaque frigo dans la liste déroulante
        while (rs.next()) {
            String item = rs.getString("idFrigo") + " - " + rs.getString("nom_frigo");
            cbofrigo.addItem(item);
        }

        rs.close();
        st.close();
        c.close();

    } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(formcreefrigo.class.getName()).log(Level.SEVERE, null, ex);
    }
                                 

//private void cbofrigoActionPerformed(java.awt.event.ActionEvent evt) {                                         
//    if (cbofrigo.getSelectedItem() != null) {
//        String frigoSelectionne = cbofrigo.getSelectedItem().toString();
//        String idFrigo = frigoSelectionne.split(" - ")[0]; // ✅ récupère l’ID avant le tiret
//        frigo.chargerBoissonsDansTable(idFrigo, tablistboisson);
//    }
//
    }//GEN-LAST:event_cbofrigoFocusGained

    private void cbofrigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbofrigoActionPerformed
        if (cbofrigo.getSelectedItem() != null) {
        String frigoSelectionne = cbofrigo.getSelectedItem().toString();
        String idFrigo = frigoSelectionne.split(" - ")[0]; // ✅ récupère l’ID avant le tiret
        frigo.chargerBoissonsDansTable(idFrigo, tablistboisson);
    }

    }//GEN-LAST:event_cbofrigoActionPerformed

    private void btnreinitialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreinitialiserActionPerformed
        // TODO add your handling code here:
        String nomFrigo = cbofrigo.getSelectedItem() != null ? cbofrigo.getSelectedItem().toString() : null;

if (nomFrigo != null) {
    int confirmation = JOptionPane.showConfirmDialog(this,
        "Voulez-vous vraiment supprimer toutes les boissons du frigo \"" + nomFrigo + "\" ?",
        "Confirmation",
        JOptionPane.YES_NO_OPTION);

    if (confirmation == JOptionPane.YES_OPTION) {
        String identifiant = creefrigo.getIdentifiantParNom(nomFrigo);
        if (identifiant != null) {
            // Sauvegarder avant suppression
            frigo.sauvegarderAvantSuppression(identifiant, nomFrigo);
            
            // Supprimer les boissons
            frigo.viderFrigo(identifiant);
            
            // Actualiser le tableau
            DefaultTableModel tm = (DefaultTableModel) tablistboisson.getModel();
            tm.setRowCount(0);
            frigo.actualiserBoissonsDuFrigo(identifiant, tm);
        } else {
            JOptionPane.showMessageDialog(this, "Identifiant du frigo introuvable.");
        }
    }
} else {
    JOptionPane.showMessageDialog(this, "Veuillez sélectionner un frigo.");
}
    }//GEN-LAST:event_btnreinitialiserActionPerformed

    private void cmbboissonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbboissonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbboissonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualiser;
    private javax.swing.JButton btnimprimer;
    private javax.swing.JButton btnnouveau;
    private javax.swing.JButton btnravitailler;
    private javax.swing.JButton btnreinitialiser;
    private javax.swing.JComboBox<String> cbofrigo;
    private javax.swing.JCheckBox ch1;
    private javax.swing.JCheckBox ch12;
    private javax.swing.JCheckBox ch24;
    private javax.swing.JCheckBox ch6;
    private javax.swing.JComboBox<String> cmbboisson;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tablistboisson;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables

}