/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package m.b;
import classe.connexionbd;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.security.MessageDigest;
import java.math.BigInteger;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author MHD
 */
public class formconnexion extends javax.swing.JPanel {
 // Variables de connexion
    private Connection c;
    private PreparedStatement ps;
    private ResultSet rs;

    // Variables pour stocker les droits
    private String nomuser;
    private int vcommande, vdepense, vfrigo, vboisson, vcaisse, vstock, vagent, vstatistique, vparametre;

 
    /**
     * Creates new form formconnexion
     */
    public formconnexion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnseconnecter = new javax.swing.JButton();
        txtmdp = new javax.swing.JPasswordField();

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setText("Identifiant");

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        jLabel2.setText("Mot de passe");

        btnseconnecter.setBackground(new java.awt.Color(0, 153, 51));
        btnseconnecter.setForeground(new java.awt.Color(255, 255, 255));
        btnseconnecter.setText("Se connecter");
        btnseconnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnseconnecterActionPerformed(evt);
            }
        });

        txtmdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmdpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnseconnecter)
                            .addComponent(txtmdp))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtmdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnseconnecter)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(340, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
        txtmdp.grabFocus();
    }//GEN-LAST:event_txtidActionPerformed

    private void btnseconnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnseconnecterActionPerformed

    String id = txtid.getText().trim();
    char[] motDePasse = txtmdp.getPassword();
    String pw = new String(motDePasse);
    String pwc = "";

    try {
        // Connexion
        c = connexionbd.seconnecter();

        // Cryptage MD5
        MessageDigest md = MessageDigest.getInstance("MD5");
        md.update(pw.getBytes(), 0, pw.length());
        pwc = new BigInteger(1, md.digest()).toString(16);

        // Requête sécurisée
        String sql = "SELECT u.nom, u.profil, "
                   + "p.commande, p.depense, p.frigo, p.boisson, p.caisse, "
                   + "p.stock, p.agent, p.statistique, p.parametre "
                   + "FROM utilisateur u "
                   + "JOIN profil p ON u.profil = p.droit "
                   + "WHERE u.identifiant = ? AND u.motdepasse = ?";

        ps = c.prepareStatement(sql);
        ps.setString(1, id);
        ps.setString(2, pwc);

        rs = ps.executeQuery();

        if (rs.next()) {
            // Récupération des infos utilisateur
            nomuser = rs.getString("nom");
            vcommande   = rs.getInt("commande");
            vdepense    = rs.getInt("depense");
            vfrigo      = rs.getInt("frigo");
            vboisson    = rs.getInt("boisson");
            vcaisse     = rs.getInt("caisse");
            vstock      = rs.getInt("stock");
            vagent      = rs.getInt("agent");
            vstatistique= rs.getInt("statistique");
            vparametre  = rs.getInt("parametre");

            // Mise à jour de l'interface principale
            formmain.lbuser.setText(nomuser);
            formmain.mconnecter.setText("Se connecter");

            // Activer/désactiver selon les droits
            formmain.mcommande.setEnabled(vcommande == 1);
            formmain.mdepense.setEnabled(vdepense == 1);
            formmain.mfrigo.setEnabled(vfrigo == 1);
            formmain.mboisson.setEnabled(vboisson == 1);
            formmain.mcaisse.setEnabled(vcaisse == 1);
            formmain.mstock.setEnabled(vstock == 1);
            formmain.magent.setEnabled(vagent == 1);
            formmain.mstatistique.setEnabled(vstatistique == 1);
            formmain.mparamètre.setEnabled(vparametre == 1);

            formmain.dbureau.removeAll();
            formmain.dbureau.repaint();

            JOptionPane.showMessageDialog(this, "Connexion réussie !");
        } else {
            JOptionPane.showMessageDialog(this, "Identifiant ou mot de passe incorrect !");
        }

    } catch (Exception ex) {
        Logger.getLogger(formconnexion.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Erreur lors de la connexion : " + ex.getMessage());
    }



    }//GEN-LAST:event_btnseconnecterActionPerformed

    private void txtmdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmdpActionPerformed
        // TODO add your handling code here:
        btnseconnecter.grabFocus();
    }//GEN-LAST:event_txtmdpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnseconnecter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JTextField txtid;
    private javax.swing.JPasswordField txtmdp;
    // End of variables declaration//GEN-END:variables
}
