/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package m.b;

import classe.agent;
import classe.connexionbd;
import classe.profil;
import classe.utilisateur;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.toedter.calendar.JDateChooser;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.sql.*;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author MHD
 */
public class formagent extends javax.swing.JPanel {

    /**
     * Creates new form formecommande
     */
    public formagent() throws SQLException {
        initComponents();
        chargerProfils();
        chargerListeAgents();
        cmbtypesalaire.removeAllItems();
cmbtypesalaire.addItem("par mois");
cmbtypesalaire.addItem("par bouteille");
cmbtypesalaire.setSelectedIndex(-1);

    }
    private int idAgentSelectionne = -1;
    private com.toedter.calendar.JDateChooser datechooser;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabagent = new javax.swing.JTable();
        btnimprimer = new javax.swing.JButton();
        btnsupprimer = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtsalaire = new javax.swing.JTextField();
        cmbprofil = new javax.swing.JComboBox<>();
        cmbtypesalaire = new javax.swing.JComboBox<>();
        btnvalider = new javax.swing.JButton();
        btnnouveau = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtprixbouteille = new javax.swing.JTextField();
        ddate = new com.toedter.calendar.JDateChooser();
        btnmodifier = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setText("                LISTE DES AGENTS");

        tabagent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Date naissance", "Profil", "Type salaire", "Nombre bouteille", "Salaire"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabagent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabagentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabagent);

        btnimprimer.setBackground(new java.awt.Color(0, 0, 0));
        btnimprimer.setForeground(new java.awt.Color(255, 255, 255));
        btnimprimer.setText("Imprimer");
        btnimprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimerActionPerformed(evt);
            }
        });

        btnsupprimer.setBackground(new java.awt.Color(153, 0, 0));
        btnsupprimer.setForeground(new java.awt.Color(255, 255, 255));
        btnsupprimer.setText("Supprimer");
        btnsupprimer.setEnabled(false);
        btnsupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsupprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(btnimprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnsupprimer)
                .addGap(125, 125, 125))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(215, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnimprimer)
                    .addComponent(btnsupprimer))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("                             ENREGISTRER AGENT");

        jLabel3.setText("Nom");

        jLabel5.setText("Date naissance");

        txtnom.setEnabled(false);
        txtnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomActionPerformed(evt);
            }
        });

        jLabel7.setText("Profil");

        jLabel8.setText("Type salaire");

        jLabel9.setText("Salaire");

        txtsalaire.setEnabled(false);
        txtsalaire.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsalaireKeyTyped(evt);
            }
        });

        cmbprofil.setEnabled(false);

        cmbtypesalaire.setEnabled(false);
        cmbtypesalaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbtypesalaireActionPerformed(evt);
            }
        });

        btnvalider.setBackground(new java.awt.Color(204, 0, 0));
        btnvalider.setForeground(new java.awt.Color(255, 255, 255));
        btnvalider.setText("Valider");
        btnvalider.setEnabled(false);
        btnvalider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvaliderActionPerformed(evt);
            }
        });

        btnnouveau.setBackground(new java.awt.Color(0, 153, 0));
        btnnouveau.setForeground(new java.awt.Color(255, 255, 255));
        btnnouveau.setText("Nouveau");
        btnnouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnouveauActionPerformed(evt);
            }
        });

        jLabel6.setText("Prix/bouteille");

        txtprixbouteille.setEnabled(false);
        txtprixbouteille.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprixbouteilleKeyTyped(evt);
            }
        });

        ddate.setEnabled(false);

        btnmodifier.setBackground(new java.awt.Color(204, 102, 0));
        btnmodifier.setForeground(new java.awt.Color(255, 255, 255));
        btnmodifier.setText("Modifier");
        btnmodifier.setEnabled(false);
        btnmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnnouveau, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnvalider)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtsalaire)
                            .addComponent(txtnom)
                            .addComponent(cmbtypesalaire, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbprofil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtprixbouteille)
                            .addComponent(ddate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(btnmodifier, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(ddate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbprofil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbtypesalaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtprixbouteille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtsalaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnouveau)
                    .addComponent(btnvalider))
                .addGap(18, 18, 18)
                .addComponent(btnmodifier)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 51));

        jLabel2.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("AGENT");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(386, 386, 386)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(283, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(525, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnvaliderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvaliderActionPerformed
        // TODO add your handling code here:
        
    btnsupprimer.setEnabled(false);
    btnmodifier.setEnabled(false);
    btnvalider.setEnabled(false);
    btnimprimer.setEnabled(true);
    tabagent.setEnabled(true);
    txtnom.setEnabled(false);
    ddate.setEnabled(false);
    cmbprofil.setEnabled(false);
    cmbtypesalaire.setEnabled(false);
    btnnouveau.setEnabled(true);
        String nom = txtnom.getText().trim();
        
if (ddate.getDate() == null) {
    JOptionPane.showMessageDialog(this, "Veuillez sélectionner une date de naissance.");
    return;
}

java.sql.Date dateNaissance = new java.sql.Date(ddate.getDate().getTime());
    String profil = cmbprofil.getSelectedItem() != null ? cmbprofil.getSelectedItem().toString() : "";
    String typeSalaire = cmbtypesalaire.getSelectedItem() != null ? cmbtypesalaire.getSelectedItem().toString() : "";
if (!verifierChampsObligatoires()) {
    return;
}
    if (nom.isEmpty() || profil.isEmpty() || typeSalaire.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs obligatoires.");
        return;
    }

    double salaire = 0;
    double prixParBouteille = 0;

    try {
        if ("par mois".equalsIgnoreCase(typeSalaire)) {
            salaire = Double.parseDouble(txtsalaire.getText().trim());
        } else if ("par bouteille".equalsIgnoreCase(typeSalaire)) {
            prixParBouteille = Double.parseDouble(txtprixbouteille.getText().trim());
        }

        agent.enregistrer(nom, (java.sql.Date) dateNaissance, profil, typeSalaire, salaire, prixParBouteille);
        JOptionPane.showMessageDialog(this, "Agent enregistré avec succès !");
        btnnouveau.doClick();
        chargerListeAgents();
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Veuillez saisir des montants valides.");
    }   catch (SQLException ex) {
            Logger.getLogger(formagent.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnvaliderActionPerformed

    private void btnnouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnouveauActionPerformed
        // TODO add your handling code here:
        
        ddate.setEnabled(true);
        txtnom.setEnabled(true);
        cmbprofil.setEnabled(true);
        cmbtypesalaire.setEnabled(true);
        txtprixbouteille.setEnabled(true);
        txtsalaire.setEnabled(true);
        btnmodifier.setEnabled(false);
        btnsupprimer.setEnabled(false);
        btnnouveau.setEnabled(false);
        btnvalider.setEnabled(true);
        txtnom.setText("");
    ddate.setDate(null);
    cmbprofil.setSelectedIndex(-1);
    cmbtypesalaire.setSelectedIndex(-1);
    txtsalaire.setText("");
    txtprixbouteille.setText("");
    txtsalaire.setEnabled(false);
    txtprixbouteille.setEnabled(false);
    txtnom.requestFocus();

    }//GEN-LAST:event_btnnouveauActionPerformed

    private void txtnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomActionPerformed

    private void btnimprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimerActionPerformed
        // TODO add your handling code here:
    btnsupprimer.setEnabled(false);
    btnmodifier.setEnabled(false);
    btnvalider.setEnabled(false);
    btnimprimer.setEnabled(true);
    tabagent.setEnabled(true);
    txtnom.setEnabled(false);
    ddate.setEnabled(false);
    cmbprofil.setEnabled(false);
    cmbtypesalaire.setEnabled(false);
    btnnouveau.setEnabled(true);
        try {
        boolean complete = tabagent.print();
        if (complete) {
            JOptionPane.showMessageDialog(this, "Impression terminée !");
        } else {
            JOptionPane.showMessageDialog(this, "Impression annulée.");
        }
    } catch (PrinterException e) {
        JOptionPane.showMessageDialog(this, "Erreur d'impression : " + e.getMessage());
    }

    }//GEN-LAST:event_btnimprimerActionPerformed

    private void cmbtypesalaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbtypesalaireActionPerformed
        // TODO add your handling code here:
        if (cmbtypesalaire.getSelectedItem() == null) return;

    String type = cmbtypesalaire.getSelectedItem().toString();
    if ("par bouteille".equalsIgnoreCase(type)) {
        txtprixbouteille.setEnabled(true);
        txtsalaire.setEnabled(false);
        txtsalaire.setText("");
    } else if ("par mois".equalsIgnoreCase(type)) {
        txtsalaire.setEnabled(true);
        txtprixbouteille.setEnabled(false);
        txtprixbouteille.setText("");
    }


    }//GEN-LAST:event_cmbtypesalaireActionPerformed
private int getIdAgentParNom(String nom) {
    int id = -1;
    try {
        Connection c = (Connection) connexionbd.seconnecter();
        PreparedStatement ps = (PreparedStatement) c.prepareStatement("SELECT id FROM agent WHERE nom = ?");
        ps.setString(1, nom);
        ResultSet rs = ps.executeQuery();
        if (rs.next()) {
            id = rs.getInt("id");
        }
        rs.close();
        ps.close();
        c.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
    return id;
}

    private void tabagentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabagentMouseClicked
           
    int ligne = tabagent.getSelectedRow();
    if (ligne == -1) {
        JOptionPane.showMessageDialog(this, "Veuillez sélectionner une ligne.");
        return;
    }

    btnsupprimer.setEnabled(true);
    btnmodifier.setEnabled(true);
    btnvalider.setEnabled(false);
    btnimprimer.setEnabled(true);
    tabagent.setEnabled(true);

    txtnom.setEnabled(true);
    ddate.setEnabled(true);
    cmbprofil.setEnabled(true);
    cmbtypesalaire.setEnabled(true);
    btnnouveau.setEnabled(true);

    txtnom.setText(tabagent.getValueAt(ligne, 0).toString());

    // ⚡ Sécurisation de la date
    Object dateObj = tabagent.getValueAt(ligne, 1);
    if (dateObj instanceof Date) {
        ddate.setDate((Date) dateObj);
    } else {
        ddate.setDate(null); // champ vide si pas de date valide
    }

    cmbprofil.setSelectedItem(tabagent.getValueAt(ligne, 2).toString());
    cmbtypesalaire.setSelectedItem(tabagent.getValueAt(ligne, 3).toString());

    String typeSalaire = tabagent.getValueAt(ligne, 3).toString();
    if ("par mois".equalsIgnoreCase(typeSalaire)) {
        txtsalaire.setEnabled(true);
        txtprixbouteille.setEnabled(false);
        txtsalaire.setText(tabagent.getValueAt(ligne, 5).toString());
        txtprixbouteille.setText("");
    } else {
        txtsalaire.setEnabled(false);
        txtprixbouteille.setEnabled(true);
        txtsalaire.setText("");
        txtprixbouteille.setText(""); 
    }

    idAgentSelectionne = getIdAgentParNom(txtnom.getText().trim());
    }//GEN-LAST:event_tabagentMouseClicked

    private void btnmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifierActionPerformed
        // TODO add your handling code here:
        
    btnsupprimer.setEnabled(false);
    btnmodifier.setEnabled(false);
    btnvalider.setEnabled(false);
    btnimprimer.setEnabled(true);
    tabagent.setEnabled(true);
    txtnom.setEnabled(false);
    ddate.setEnabled(false);
    cmbprofil.setEnabled(false);
    cmbtypesalaire.setEnabled(false);
    btnnouveau.setEnabled(true);

    if (!verifierChampsObligatoires()) {
        return;
    }

    if (idAgentSelectionne == -1) {
        JOptionPane.showMessageDialog(this, "Veuillez sélectionner un agent à modifier.");
        return;
    }

    String nom = txtnom.getText().trim();

    // ⚡ Sécurisation de la date
    java.sql.Date dateNaissance = null;
    if (ddate.getDate() != null) {
        dateNaissance = new java.sql.Date(ddate.getDate().getTime());
    }

    String profil = cmbprofil.getSelectedItem().toString();
    String typeSalaire = cmbtypesalaire.getSelectedItem().toString();

    double salaire = 0;
    double prixParBouteille = 0;

    try {
        if ("par mois".equalsIgnoreCase(typeSalaire)) {
            salaire = Double.parseDouble(txtsalaire.getText().trim());
        } else {
            prixParBouteille = Double.parseDouble(txtprixbouteille.getText().trim());
        }

        agent.modifier(idAgentSelectionne, nom, dateNaissance, profil, typeSalaire, salaire, prixParBouteille);
        JOptionPane.showMessageDialog(this, "Agent modifié !");
        chargerListeAgents();
//        btnnouveau.doClick();

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Montants invalides.");
    } catch (SQLException ex) {
        Logger.getLogger(formagent.class.getName()).log(Level.SEVERE, null, ex);
    }
//    btnsupprimer.setEnabled(false);
//    btnmodifier.setEnabled(false);
//    btnvalider.setEnabled(false);
//    btnimprimer.setEnabled(true);
//    tabagent.setEnabled(true);
//    txtnom.setEnabled(false);
//    ddate.setEnabled(false);
//    cmbprofil.setEnabled(false);
//    cmbtypesalaire.setEnabled(false);
//    btnnouveau.setEnabled(true);
//    if (!verifierChampsObligatoires()) {
//    return;
//}
// if (idAgentSelectionne == -1) {
//        JOptionPane.showMessageDialog(this, "Veuillez sélectionner un agent à modifier.");
//        return;
//    }
//
//    String nom = txtnom.getText().trim();
//    java.sql.Date dateNaissance = new java.sql.Date(ddate.getDate().getTime());
//    String profil = cmbprofil.getSelectedItem().toString(); // ✅ ajout de la ligne manquante
//    String typeSalaire = cmbtypesalaire.getSelectedItem().toString();
//    double salaire = 0;
//    double prixParBouteille = 0;
//
//    try {
//        if ("par mois".equalsIgnoreCase(typeSalaire)) {
//            salaire = Double.parseDouble(txtsalaire.getText().trim());
//        } else {
//            prixParBouteille = Double.parseDouble(txtprixbouteille.getText().trim());
//        }
//
//        agent.modifier(idAgentSelectionne, nom, dateNaissance, profil, typeSalaire, salaire, prixParBouteille);
//        JOptionPane.showMessageDialog(this, "Agent modifié !");
//        chargerListeAgents();
//        btnnouveau.doClick();
//    } catch (NumberFormatException e) {
//        JOptionPane.showMessageDialog(this, "Montants invalides.");
//    }   catch (SQLException ex) {
//            Logger.getLogger(formagent.class.getName()).log(Level.SEVERE, null, ex);
//        }


    }//GEN-LAST:event_btnmodifierActionPerformed

    private void btnsupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsupprimerActionPerformed
        // TODO add your handling code here:
    btnsupprimer.setEnabled(false);
    btnmodifier.setEnabled(false);
    btnvalider.setEnabled(false);
    btnimprimer.setEnabled(true);
    tabagent.setEnabled(true);
    txtnom.setEnabled(false);
    ddate.setEnabled(false);
    cmbprofil.setEnabled(false);
    cmbtypesalaire.setEnabled(false);
    btnnouveau.setEnabled(true);
         if (idAgentSelectionne == -1) {
        JOptionPane.showMessageDialog(this, "Veuillez sélectionner un agent à supprimer.");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this, "Confirmer la suppression de cet agent ?", "Confirmation", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        agent.supprimer(idAgentSelectionne);
        JOptionPane.showMessageDialog(this, "Agent supprimé !");
             try {
                 chargerListeAgents();
             } catch (SQLException ex) {
                 Logger.getLogger(formagent.class.getName()).log(Level.SEVERE, null, ex);
             }
//        btnnouveau.doClick();
    }

    }//GEN-LAST:event_btnsupprimerActionPerformed

    private void txtprixbouteilleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprixbouteilleKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE)){
        getToolkit().beep();
        evt.consume();
    }     
    }//GEN-LAST:event_txtprixbouteilleKeyTyped

    private void txtsalaireKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsalaireKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE)){
        getToolkit().beep();
        evt.consume();
    }     
    }//GEN-LAST:event_txtsalaireKeyTyped

    private void chargerListeAgents() throws SQLException {
    DefaultTableModel model = (DefaultTableModel) tabagent.getModel();
    model.setRowCount(0);

    Vector<Vector<Object>> lignes = agent.getListeAgents();
    for (Vector<Object> ligne : lignes) {
        model.addRow(ligne);
    }
}
    
    private void chargerProfils() {
    cmbprofil.removeAllItems();
    Vector<String> profils = utilisateur.getListeProfils(); // ou une autre classe selon ta structure
    for (String p : profils) {
        cmbprofil.addItem(p);
    }
}
    
    private boolean verifierChampsObligatoires() {
    if (txtnom.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Veuillez saisir le nom de l'agent.");
        txtnom.requestFocus();
        return false;
    }

    if (ddate.getDate() == null) {
        JOptionPane.showMessageDialog(this, "Veuillez sélectionner une date de naissance.");
        ddate.requestFocus();
        return false;
    }

    if (cmbprofil.getSelectedIndex() == -1) {
        JOptionPane.showMessageDialog(this, "Veuillez sélectionner un profil.");
        cmbprofil.requestFocus();
        return false;
    }

    if (cmbtypesalaire.getSelectedIndex() == -1) {
        JOptionPane.showMessageDialog(this, "Veuillez sélectionner un type de salaire.");
        cmbtypesalaire.requestFocus();
        return false;
    }

    String typeSalaire = cmbtypesalaire.getSelectedItem().toString();
    if ("par mois".equalsIgnoreCase(typeSalaire)) {
        if (txtsalaire.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Veuillez saisir le salaire mensuel.");
            txtsalaire.requestFocus();
            return false;
        }
    } else {
        if (txtprixbouteille.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Veuillez saisir le prix par bouteille.");
            txtprixbouteille.requestFocus();
            return false;
        }
    }

    return true;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnimprimer;
    private javax.swing.JButton btnmodifier;
    private javax.swing.JButton btnnouveau;
    private javax.swing.JButton btnsupprimer;
    private javax.swing.JButton btnvalider;
    private javax.swing.JComboBox<String> cmbprofil;
    private javax.swing.JComboBox<String> cmbtypesalaire;
    private com.toedter.calendar.JDateChooser ddate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tabagent;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtprixbouteille;
    private javax.swing.JTextField txtsalaire;
    // End of variables declaration//GEN-END:variables
}
