/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package m.b;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;


/**
 *
 * @author MHD
 */
public class formmain extends javax.swing.JFrame {
public static int vcom = 0, vdep = 0, vpar=0, vfri=0, vboi=0, vcai=0, vsto=0, vage=0,vsta=0;
public static String nomuser="";
    /**
     * Creates new form formmain
     */
    public formmain() {
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screenSize.width, screenSize.height); // occupe tout l’écran
        this.setLocationRelativeTo(null); // centré
        this.setResizable(false);


            // Menus désactivés par défaut
    mcommande.setEnabled(false);
    mdepense.setEnabled(false);
    mfrigo.setEnabled(false);
    mboisson.setEnabled(false);
    mstock.setEnabled(false);
    magent.setEnabled(false);
    mstatistique.setEnabled(false);
    mparamètre.setEnabled(false);
    mcaisse.setEnabled(false); // si tu veux aussi désactiver le menu caisse

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mcommande = new javax.swing.JLabel();
        mdepense = new javax.swing.JLabel();
        mfrigo = new javax.swing.JLabel();
        mcaisse = new javax.swing.JLabel();
        mstock = new javax.swing.JLabel();
        magent = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        mparamètre = new javax.swing.JLabel();
        mstatistique = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        mboisson = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        mconnecter = new javax.swing.JLabel();
        lbuser = new javax.swing.JLabel();
        dbureau = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        maccueil = new javax.swing.JMenu();
        maide = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        mcommande.setBackground(new java.awt.Color(255, 255, 255));
        mcommande.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        mcommande.setForeground(new java.awt.Color(255, 255, 255));
        mcommande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/commande_b.png"))); // NOI18N
        mcommande.setText("Commande");
        mcommande.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mcommande.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mcommandeMouseClicked(evt);
            }
        });

        mdepense.setBackground(new java.awt.Color(255, 255, 255));
        mdepense.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        mdepense.setForeground(new java.awt.Color(255, 255, 255));
        mdepense.setText("Depenses");
        mdepense.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mdepense.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mdepenseMouseClicked(evt);
            }
        });

        mfrigo.setBackground(new java.awt.Color(255, 255, 255));
        mfrigo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        mfrigo.setForeground(new java.awt.Color(255, 255, 255));
        mfrigo.setText("Frigo");
        mfrigo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mfrigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mfrigoMouseClicked(evt);
            }
        });

        mcaisse.setBackground(new java.awt.Color(255, 255, 255));
        mcaisse.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        mcaisse.setForeground(new java.awt.Color(255, 255, 255));
        mcaisse.setText("Caisse");
        mcaisse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mcaisse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mcaisseMouseClicked(evt);
            }
        });

        mstock.setBackground(new java.awt.Color(255, 255, 255));
        mstock.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        mstock.setForeground(new java.awt.Color(255, 255, 255));
        mstock.setText("Stock");
        mstock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mstock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mstockMouseClicked(evt);
            }
        });

        magent.setBackground(new java.awt.Color(255, 255, 255));
        magent.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        magent.setForeground(new java.awt.Color(255, 255, 255));
        magent.setText("Agents");
        magent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        magent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                magentMouseClicked(evt);
            }
        });

        mparamètre.setBackground(new java.awt.Color(255, 255, 255));
        mparamètre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        mparamètre.setForeground(new java.awt.Color(255, 255, 255));
        mparamètre.setText("Paramètres");
        mparamètre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mparamètre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mparamètreMouseClicked(evt);
            }
        });

        mstatistique.setBackground(new java.awt.Color(255, 255, 255));
        mstatistique.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        mstatistique.setForeground(new java.awt.Color(255, 255, 255));
        mstatistique.setText("Statistiques");
        mstatistique.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mstatistique.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mstatistiqueMouseClicked(evt);
            }
        });

        mboisson.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        mboisson.setForeground(new java.awt.Color(255, 255, 255));
        mboisson.setText("Boisson");
        mboisson.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mboisson.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mboissonMouseClicked(evt);
            }
        });

        mconnecter.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        mconnecter.setForeground(new java.awt.Color(255, 255, 255));
        mconnecter.setText("Se connecter");
        mconnecter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mconnecter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mconnecterMouseClicked(evt);
            }
        });

        lbuser.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        lbuser.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator8)
            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mcommande, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mdepense, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(mfrigo, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(mboisson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mstatistique, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mcaisse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(magent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(mstock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(mparamètre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbuser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mconnecter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mcommande, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mdepense)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mfrigo)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mboisson)
                .addGap(18, 18, 18)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mcaisse)
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mstock)
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(magent)
                .addGap(18, 18, 18)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mstatistique)
                .addGap(18, 18, 18)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mparamètre)
                .addGap(18, 18, 18)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mconnecter)
                .addGap(18, 18, 18)
                .addComponent(lbuser, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dbureau.setBackground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout dbureauLayout = new javax.swing.GroupLayout(dbureau);
        dbureau.setLayout(dbureauLayout);
        dbureauLayout.setHorizontalGroup(
            dbureauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );
        dbureauLayout.setVerticalGroup(
            dbureauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 683, Short.MAX_VALUE)
        );

        maccueil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home_32.png"))); // NOI18N
        maccueil.setText("Accueil");
        maccueil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.add(maccueil);

        maide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/help_32.png"))); // NOI18N
        maide.setText("Aide");
        maide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.add(maide);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dbureau)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dbureau)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mcommandeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mcommandeMouseClicked
        // TODO add your handling code here:
         if (!mcommande.isEnabled()) {
        // Si le menu est désactivé, on ne fait rien
        return;
    }
        dbureau.removeAll();// vidé
        dbureau.repaint();//actualisé
        formecommande fcom = new formecommande();
        fcom.setSize(dbureau.getWidth(),dbureau.getHeight());
        fcom.setVisible(true);
        dbureau.add(fcom);
//         formmain.mfrigo.setEnabled(vfri == 1);
//    formmain.mdepense.setEnabled(vdep == 1);
//    formmain.mcaisse.setEnabled(vcai == 1);
//    formmain.mboisson.setEnabled(vboi == 1);
//    formmain.mstock.setEnabled(vsto == 1);
//    formmain.magent.setEnabled(vage == 1);
//    formmain.mstatistique.setEnabled(vsta == 1);
//    formmain.mparamètre.setEnabled(vpar == 1);
    }//GEN-LAST:event_mcommandeMouseClicked

    private void mdepenseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mdepenseMouseClicked
        // TODO add your handling code here:
         if (!mdepense.isEnabled()) {
        // Si le menu est désactivé, on ne fait rien
        return;
    }
        dbureau.removeAll();// vidé
        dbureau.repaint();//actualisé
        formdepense fdepense = new formdepense();
        fdepense.setSize(dbureau.getWidth(),dbureau.getHeight());
        fdepense.setVisible(true);
        dbureau.add(fdepense);
//         formmain.mcommande.setEnabled(vcom == 1);
//    formmain.mfrigo.setEnabled(vfri == 1);
//    formmain.mcaisse.setEnabled(vcai == 1);
//    formmain.mboisson.setEnabled(vboi == 1);
//    formmain.mstock.setEnabled(vsto == 1);
//    formmain.magent.setEnabled(vage == 1);
//    formmain.mstatistique.setEnabled(vsta == 1);
//    formmain.mparamètre.setEnabled(vpar == 1);
    }//GEN-LAST:event_mdepenseMouseClicked

    private void mfrigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mfrigoMouseClicked
        // TODO add your handling code here:
         if (!mfrigo.isEnabled()) {
        // Si le menu est désactivé, on ne fait rien
        return;
    }
        dbureau.removeAll();// vidé
        dbureau.repaint();//actualisé
        formfrigo ffrigo = new formfrigo();
        ffrigo.setSize(dbureau.getWidth(),dbureau.getHeight());
        ffrigo.setVisible(true);
        dbureau.add(ffrigo);
        
//         formmain.mcommande.setEnabled(vcom == 1);
//    formmain.mdepense.setEnabled(vdep == 1);
//    formmain.mcaisse.setEnabled(vcai == 1);
//    formmain.mboisson.setEnabled(vboi == 1);
//    formmain.mstock.setEnabled(vsto == 1);
//    formmain.magent.setEnabled(vage == 1);
//    formmain.mstatistique.setEnabled(vsta == 1);
//    formmain.mparamètre.setEnabled(vpar == 1);
    }//GEN-LAST:event_mfrigoMouseClicked

    private void mcaisseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mcaisseMouseClicked
        // TODO add your handling code here:
        
        if (!mcaisse.isEnabled()) {
        // Si le menu est désactivé, on ne fait rien
        return;
    }

    // Sinon, exécuter le code normal
    dbureau.removeAll();
    dbureau.repaint();
    formcaisse fcaisse = new formcaisse();
    fcaisse.setSize(dbureau.getWidth(), dbureau.getHeight());
    fcaisse.setVisible(true);
    dbureau.add(fcaisse);

//    // Activer/désactiver les sous-menus selon les droits
//    formmain.mcommande.setEnabled(vcom == 1);
//    formmain.mdepense.setEnabled(vdep == 1);
//    formmain.mfrigo.setEnabled(vfri == 1);
//    formmain.mboisson.setEnabled(vboi == 1);
//    formmain.mstock.setEnabled(vsto == 1);
//    formmain.magent.setEnabled(vage == 1);
//    formmain.mstatistique.setEnabled(vsta == 1);
//    formmain.mparamètre.setEnabled(vpar == 1);
        

    }//GEN-LAST:event_mcaisseMouseClicked

    private void mstockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mstockMouseClicked
        // TODO add your handling code here:
         if (!mstock.isEnabled()) {
        // Si le menu est désactivé, on ne fait rien
        return;
    }
        dbureau.removeAll();// vidé
        dbureau.repaint();//actualisé
        formstock fstock = new formstock();
        fstock.setSize(dbureau.getWidth(),dbureau.getHeight());
        fstock.setVisible(true);
        dbureau.add(fstock);
//        formmain.mcommande.setEnabled(vcom == 1);
//    formmain.mdepense.setEnabled(vdep == 1);
//    formmain.mfrigo.setEnabled(vfri == 1);
//    formmain.mboisson.setEnabled(vboi == 1);
//    formmain.mcaisse.setEnabled(vcai == 1);
//    formmain.magent.setEnabled(vage == 1);
//    formmain.mstatistique.setEnabled(vsta == 1);
//    formmain.mparamètre.setEnabled(vpar == 1);
    }//GEN-LAST:event_mstockMouseClicked

    private void magentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_magentMouseClicked
       
        if (!magent.isEnabled()) {
        // Si le menu est désactivé, on ne fait rien
        return;
    }
        
        try {
            // TODO add your handling code here:
            dbureau.removeAll();// vidé
            dbureau.repaint();//actualisé
            formagent fagent = new formagent();
            fagent.setSize(dbureau.getWidth(),dbureau.getHeight());
            fagent.setVisible(true);
            dbureau.add(fagent);
        } catch (SQLException ex) {
            Logger.getLogger(formmain.class.getName()).log(Level.SEVERE, null, ex);
        }
//         formmain.mcommande.setEnabled(vcom == 1);
//    formmain.mdepense.setEnabled(vdep == 1);
//    formmain.mfrigo.setEnabled(vfri == 1);
//    formmain.mboisson.setEnabled(vboi == 1);
//    formmain.mcaisse.setEnabled(vcai == 1);
//    formmain.mstock.setEnabled(vsto == 1);
//    formmain.mstatistique.setEnabled(vsta == 1);
//    formmain.mparamètre.setEnabled(vpar == 1);
    }//GEN-LAST:event_magentMouseClicked

    private void mstatistiqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mstatistiqueMouseClicked
        // TODO add your handling code here:
       if (!mstatistique.isEnabled()) {
        // Si le menu est désactivé, on ne fait rien
        return;
    }
        dbureau.removeAll();// vidé
        dbureau.repaint();//actualisé
        formstatistiques fstatistiques = new formstatistiques();
        fstatistiques.setSize(dbureau.getWidth(),dbureau.getHeight());
        fstatistiques.setVisible(true);
        dbureau.add(fstatistiques);
        
//        formmain.mcommande.setEnabled(vcom == 1);
//    formmain.mdepense.setEnabled(vdep == 1);
//    formmain.mfrigo.setEnabled(vfri == 1);
//    formmain.mboisson.setEnabled(vboi == 1);
//    formmain.mcaisse.setEnabled(vcai == 1);
//    formmain.mstock.setEnabled(vsto == 1);
//    formmain.magent.setEnabled(vage == 1);
//    formmain.mparamètre.setEnabled(vpar == 1);
        
    }//GEN-LAST:event_mstatistiqueMouseClicked

    private void mparamètreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mparamètreMouseClicked
        // TODO add your handling code here:
          if (!mparamètre.isEnabled()) {
        // Si le menu est désactivé, on ne fait rien
        return;
    }
        dbureau.removeAll();// vidé
        dbureau.repaint();//actualisé
        formparametre fparametre = new formparametre();
        fparametre.setSize(dbureau.getWidth(),dbureau.getHeight());
        fparametre.setVisible(true);
        dbureau.add(fparametre);
//        formmain.mcommande.setEnabled(vcom == 1);
//    formmain.mdepense.setEnabled(vdep == 1);
//    formmain.mfrigo.setEnabled(vfri == 1);
//    formmain.mboisson.setEnabled(vboi == 1);
//    formmain.mcaisse.setEnabled(vcai == 1);
//    formmain.mstock.setEnabled(vsto == 1);
//    formmain.magent.setEnabled(vage == 1);
//    formmain.mstatistique.setEnabled(vsta == 1);
    }//GEN-LAST:event_mparamètreMouseClicked

    private void mboissonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mboissonMouseClicked
        // TODO add your handling code here:
          if (!mboisson.isEnabled()) {
        // Si le menu est désactivé, on ne fait rien
        return;
    }
        dbureau.removeAll();// vidé
        dbureau.repaint();//actualisé
        formboisson fbois = new formboisson();
        fbois.setSize(dbureau.getWidth(),dbureau.getHeight());
        fbois.setVisible(true);
        dbureau.add(fbois);
//        formmain.mcommande.setEnabled(vcom == 1);
//    formmain.mdepense.setEnabled(vdep == 1);
//    formmain.mfrigo.setEnabled(vfri == 1);
//    formmain.mparamètre.setEnabled(vpar == 1);
//    formmain.mcaisse.setEnabled(vcai == 1);
//    formmain.mstock.setEnabled(vsto == 1);
//    formmain.magent.setEnabled(vage == 1);
//    formmain.mstatistique.setEnabled(vsta == 1);
    }//GEN-LAST:event_mboissonMouseClicked

    private void mconnecterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mconnecterMouseClicked
        // TODO add your handling code here:
        dbureau.removeAll();// vidé
        dbureau.repaint();//actualisé
        formconnexion fconn = new formconnexion();
        fconn.setSize(dbureau.getWidth(),dbureau.getHeight());
        fconn.setVisible(true);
        dbureau.add(fconn);
        
    }//GEN-LAST:event_mconnecterMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formmain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formmain().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane dbureau;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    public static javax.swing.JLabel lbuser;
    private javax.swing.JMenu maccueil;
    public static javax.swing.JLabel magent;
    private javax.swing.JMenu maide;
    public static javax.swing.JLabel mboisson;
    public static javax.swing.JLabel mcaisse;
    public static javax.swing.JLabel mcommande;
    public static javax.swing.JLabel mconnecter;
    public static javax.swing.JLabel mdepense;
    public static javax.swing.JLabel mfrigo;
    public static javax.swing.JLabel mparamètre;
    public static javax.swing.JLabel mstatistique;
    public static javax.swing.JLabel mstock;
    // End of variables declaration//GEN-END:variables
}
